//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A__plant_Error_Save
    {
        public long Id { get; set; }
        public string PageName { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime Date { get; set; }
        public string FunctionName { get; set; }
        public string User_Ip { get; set; }
        public bool IsWeb { get; set; }
    }
}
