//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A__User_Login
    {
        public long Id { get; set; }
        public long User_Id { get; set; }
        public System.DateTime Login_Date { get; set; }
        public Nullable<System.DateTime> LogOut_Date { get; set; }
        public string AccessToken { get; set; }
    }
}
