//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_AttachmentTableName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_AttachmentTableName()
        {
            this.A_AttachmentData = new HashSet<A_AttachmentData>();
            this.A_AttachmentData_Ex_CheckRequest = new HashSet<A_AttachmentData_Ex_CheckRequest>();
            this.A_AttachmentData_Station = new HashSet<A_AttachmentData_Station>();
            this.Table_Action = new HashSet<Table_Action>();
        }
    
        public short ID { get; set; }
        public string TableName { get; set; }
        public string Description { get; set; }
        public Nullable<byte> PR_Module_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_AttachmentData> A_AttachmentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_AttachmentData_Ex_CheckRequest> A_AttachmentData_Ex_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_AttachmentData_Station> A_AttachmentData_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Action> Table_Action { get; set; }
    }
}
