//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_AttachmentTableType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_AttachmentTableType()
        {
            this.A_AttachmentData = new HashSet<A_AttachmentData>();
            this.A_AttachmentData_Ex_CheckRequest = new HashSet<A_AttachmentData_Ex_CheckRequest>();
            this.A_AttachmentData_Station = new HashSet<A_AttachmentData_Station>();
            this.Ex_CertificatesRequestsFiles = new HashSet<Ex_CertificatesRequestsFiles>();
        }
    
        public short ID { get; set; }
        public string Ar_Name { get; set; }
        public string En_Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> opration_type_attachment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_AttachmentData> A_AttachmentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_AttachmentData_Ex_CheckRequest> A_AttachmentData_Ex_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_AttachmentData_Station> A_AttachmentData_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CertificatesRequestsFiles> Ex_CertificatesRequestsFiles { get; set; }
    }
}
