//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisLabType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnalysisLabType()
        {
            this.Ex_CheckRequest_SampleData = new HashSet<Ex_CheckRequest_SampleData>();
            this.EX_Choose_SampleData = new HashSet<EX_Choose_SampleData>();
            this.Farm_SampleData = new HashSet<Farm_SampleData>();
            this.Farm_SampleData_Item = new HashSet<Farm_SampleData_Item>();
            this.Im_CheckRequest_SampleData = new HashSet<Im_CheckRequest_SampleData>();
        }
    
        public int ID { get; set; }
        public int AnalysisLabID { get; set; }
        public int AnalysisTypeID { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
    
        public virtual AnalysisLab AnalysisLab { get; set; }
        public virtual AnalysisType AnalysisType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_SampleData> Ex_CheckRequest_SampleData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EX_Choose_SampleData> EX_Choose_SampleData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_SampleData> Farm_SampleData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_SampleData_Item> Farm_SampleData_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_SampleData> Im_CheckRequest_SampleData { get; set; }
    }
}
