//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Andriod_Location
    {
        public long Id { get; set; }
        public long Committe_ID { get; set; }
        public bool IsExport { get; set; }
        public byte Operation_ID { get; set; }
        public long User_Id { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public System.DateTime Created_Date { get; set; }
    
        public virtual Andriod_Operation Andriod_Operation { get; set; }
    }
}
