//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAccreditation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyAccreditation()
        {
            this.CompanyAccreditation_Committee = new HashSet<CompanyAccreditation_Committee>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Company_ID { get; set; }
        public Nullable<short> Country_ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<long> Item_ShortName_id { get; set; }
    
        public virtual Company_National Company_National { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyAccreditation_Committee> CompanyAccreditation_Committee { get; set; }
        public virtual Country Country { get; set; }
        public virtual Item_ShortName Item_ShortName { get; set; }
    }
}
