//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyActivity
    {
        public long ID { get; set; }
        public Nullable<long> Company_ID { get; set; }
        public Nullable<byte> CompActivityType_ID { get; set; }
        public int MainActivityType { get; set; }
        public string Enrollment_Name { get; set; }
        public Nullable<decimal> Enrollment_Number { get; set; }
        public Nullable<System.DateTime> Enrollment_Start { get; set; }
        public Nullable<System.DateTime> Enrollment_End { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<byte> Enrollment_type_ID { get; set; }
    
        public virtual A_SystemCode A_SystemCode { get; set; }
        public virtual Company_National Company_National { get; set; }
        public virtual CompanyActivityType CompanyActivityType { get; set; }
        public virtual Enrollment_type Enrollment_type { get; set; }
    }
}
