//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAccreditation_Payment
    {
        public long ID { get; set; }
        public long Company_Committee_ID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public bool IS_OnlineOffline { get; set; }
        public short User_Creation_Id { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
    
        public virtual CompanyAccreditation_Committee CompanyAccreditation_Committee { get; set; }
    }
}
