//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX
    {
        public string CheckRequest_Number { get; set; }
        public long Ex_CheckRequest_ID { get; set; }
        public Nullable<long> Ex_CheckRequest_Items_ID { get; set; }
        public Nullable<byte> CommitteeType_ID { get; set; }
        public long Committee_ID { get; set; }
        public Nullable<long> LotData_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsAdminResult { get; set; }
        public Nullable<double> QuantitySize { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IS_Total { get; set; }
        public Nullable<long> Item_ShortName_ID { get; set; }
        public Nullable<System.DateTime> Delegation_Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<bool> IsFinishedAll { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ShortName_Ar { get; set; }
        public string ShortName_En { get; set; }
        public Nullable<long> Expr1 { get; set; }
        public long Ex_CommitteeResult_ID { get; set; }
        public System.DateTime Expr2 { get; set; }
        public long EmployeeId { get; set; }
        public string Expr3 { get; set; }
        public bool IsAccepted { get; set; }
    }
}
