//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CertificatesRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_CertificatesRequests()
        {
            this.Ex_CertificateAddtion = new HashSet<Ex_CertificateAddtion>();
            this.Ex_CertificateAddtionUser = new HashSet<Ex_CertificateAddtionUser>();
            this.Ex_CheckRequest_Customs_Message = new HashSet<Ex_CheckRequest_Customs_Message>();
            this.Fees_Certificates_Payment_Detiles = new HashSet<Fees_Certificates_Payment_Detiles>();
            this.Ex_CertificatesRequestsFiles = new HashSet<Ex_CertificatesRequestsFiles>();
            this.Ex_CertificatesRequestsLotData = new HashSet<Ex_CertificatesRequestsLotData>();
            this.Ex_CertificatesRequestsPayments = new HashSet<Ex_CertificatesRequestsPayments>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Ex_CheckRequest_ID { get; set; }
        public string ShippingPolicyNumber { get; set; }
        public string ShippingCompanyName { get; set; }
        public Nullable<long> ShipmentmeanID { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public string ShippingAgency { get; set; }
        public long Importer_Id { get; set; }
        public int ExporterId { get; set; }
        public long ExporterTypeID { get; set; }
        public string Details { get; set; }
        public string CertificateNumber { get; set; }
        public int CertificateNo { get; set; }
        public int ArrivePortID { get; set; }
        public Nullable<bool> ISAccepted { get; set; }
        public bool ISPrint { get; set; }
        public Nullable<bool> ISEnglish { get; set; }
        public Nullable<long> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<bool> IS_Lot { get; set; }
        public Nullable<bool> IS_Containers { get; set; }
        public Nullable<bool> IS_Treatment { get; set; }
        public Nullable<bool> IS_Additional_Declaretion { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<byte> Transport_Mean_Id { get; set; }
        public string Ship_Name { get; set; }
        public Nullable<long> InternationalTransportation_ID { get; set; }
        public string ImportCompany_Name_EN { get; set; }
        public string ImporeterCompanyAddress_EN { get; set; }
        public string ImportCompany_Name_AR { get; set; }
        public string ImporeterCompanyAddress_AR { get; set; }
        public Nullable<int> Shipping_Port { get; set; }
        public short Importing_Country { get; set; }
        public byte Port_Type_Importing_Country { get; set; }
        public Nullable<int> Port_Access { get; set; }
        public Nullable<short> Transit_Country { get; set; }
        public Nullable<byte> Port_Type_Transit_Country { get; set; }
        public Nullable<int> Transit_Port { get; set; }
        public string RejectReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CertificateAddtion> Ex_CertificateAddtion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CertificateAddtionUser> Ex_CertificateAddtionUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Customs_Message> Ex_CheckRequest_Customs_Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fees_Certificates_Payment_Detiles> Fees_Certificates_Payment_Detiles { get; set; }
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CertificatesRequestsFiles> Ex_CertificatesRequestsFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CertificatesRequestsLotData> Ex_CertificatesRequestsLotData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CertificatesRequestsPayments> Ex_CertificatesRequestsPayments { get; set; }
    }
}
