//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest_Places
    {
        public long ID { get; set; }
        public long Ex_CheckRequest_ID { get; set; }
        public Nullable<int> PortNational_ID { get; set; }
        public Nullable<short> Center_ID { get; set; }
        public Nullable<short> Govern_ID { get; set; }
        public Nullable<long> Station_Genshi_ID { get; set; }
        public Nullable<long> Station_Examination_ID { get; set; }
        public string Examination_location { get; set; }
        public Nullable<long> Station_Accreditation_Data_Examination_ID { get; set; }
        public Nullable<long> Outlet_Exmainiation_ID { get; set; }
        public Nullable<long> Outlet_Genshi_ID { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        public virtual Governate Governate { get; set; }
        public virtual PortNational PortNational { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
