//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest_Items_Lot_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_CheckRequest_Items_Lot_Category()
        {
            this.Ex_CheckRequest_Items_Lot_Result = new HashSet<Ex_CheckRequest_Items_Lot_Result>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Ex_CheckRequest_Items_ID { get; set; }
        public Nullable<short> Package_Material_ID { get; set; }
        public Nullable<short> Package_Type_ID { get; set; }
        public Nullable<int> Package_Count { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> Net_Weight { get; set; }
        public Nullable<decimal> Based_Weight { get; set; }
        public Nullable<decimal> Package_Weight { get; set; }
        public Nullable<decimal> Package_Based_Weight { get; set; }
        public Nullable<decimal> Package_Net_Weight { get; set; }
        public Nullable<int> Units_Number { get; set; }
        public Nullable<double> Size { get; set; }
        public string Order_Text { get; set; }
        public string Reason_Entry { get; set; }
        public string Lot_Number { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public string RejectReason { get; set; }
        public string Grower_Number { get; set; }
        public string Waybill { get; set; }
        public string Number_Wooden_Package { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<long> Ex_CheckRequset_Shipping_MethodID { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<long> User_Updation_Id { get; set; }
        public Nullable<decimal> GrossWeightOld { get; set; }
        public Nullable<long> FarmsData_ID { get; set; }
        public string FarmsCode { get; set; }
    
        public virtual Ex_CheckRequest_Items Ex_CheckRequest_Items { get; set; }
        public virtual Ex_CheckRequset_Shipping_Method Ex_CheckRequset_Shipping_Method { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Items_Lot_Result> Ex_CheckRequest_Items_Lot_Result { get; set; }
    }
}
