//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CertificateAddtionUser
    {
        public long ID { get; set; }
        public Nullable<long> PlantCertificatesRequestsID { get; set; }
        public string Certificate_AddtionText { get; set; }
        public Nullable<bool> IS_Client_OR_Agree { get; set; }
    
        public virtual Ex_CertificatesRequests Ex_CertificatesRequests { get; set; }
    }
}
