//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest_Customs_Message
    {
        public int ID { get; set; }
        public Nullable<long> Ex_CheckRequest_ID { get; set; }
        public Nullable<long> Ex_CertificatesRequests_ID { get; set; }
        public string Customs_Certificate_Number { get; set; }
        public Nullable<System.DateTime> Certification_Date { get; set; }
        public Nullable<System.DateTime> Shipment_Date { get; set; }
        public Nullable<System.DateTime> Arrival_Date { get; set; }
        public string Certificate_Number_Each_Product { get; set; }
        public string Manifest_Number { get; set; }
        public Nullable<long> Shipping_Agency_ID { get; set; }
        public Nullable<byte> Im_OperationType { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Ex_CertificatesRequests Ex_CertificatesRequests { get; set; }
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        public virtual ShippingAgency ShippingAgency { get; set; }
    }
}
