//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_CheckRequest_Data()
        {
            this.Ex_CheckRequest_Port = new HashSet<Ex_CheckRequest_Port>();
            this.Ex_CheckRequestData_Extra = new HashSet<Ex_CheckRequestData_Extra>();
        }
    
        public long ID { get; set; }
        public long Importer_ID { get; set; }
        public int ImporterType_Id { get; set; }
        public Nullable<short> ExportCountry_Id { get; set; }
        public Nullable<byte> Shipment_Mean_Id { get; set; }
        public Nullable<byte> Transport_Mean_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<long> Ex_CheckRequest_ID { get; set; }
        public string Ship_Name { get; set; }
        public string DelegateName { get; set; }
        public string DelegateAddress { get; set; }
        public Nullable<short> TransitCountry_Id { get; set; }
        public Nullable<long> InternationalTransportation_ID { get; set; }
        public Nullable<long> Transit_Regions_ID { get; set; }
        public Nullable<long> Export_Regions_ID { get; set; }
        public Nullable<short> Governate_ID { get; set; }
        public Nullable<long> ShippingCompanies_ID { get; set; }
        public string NationalIDCompanyOwner { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        public virtual InternationalTransportation InternationalTransportation { get; set; }
        public virtual Shipment_Mean Shipment_Mean { get; set; }
        public virtual ShippingCompany ShippingCompany { get; set; }
        public virtual Transport_Mean Transport_Mean { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Port> Ex_CheckRequest_Port { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequestData_Extra> Ex_CheckRequestData_Extra { get; set; }
    }
}
