//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest_Visa
    {
        public long ID { get; set; }
        public Nullable<long> Ex_Visa_ID { get; set; }
        public Nullable<long> Ex_CheckRequest_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
    
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        public virtual Im_Visa Im_Visa { get; set; }
        public virtual Ex_Visa Ex_Visa { get; set; }
    }
}
