//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CertificatesRequestsPaymentsDetailes
    {
        public long ID { get; set; }
        public Nullable<long> Ex_CertificatesRequestsPaymentsID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<bool> IsSuccess_Bank { get; set; }
        public string Code_Bank { get; set; }
        public Nullable<int> User_Type_ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public Nullable<long> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
    
        public virtual Ex_CertificatesRequestsPayments Ex_CertificatesRequestsPayments { get; set; }
    }
}
