//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Constran
    {
        public Nullable<short> Import_Country_ID { get; set; }
        public Nullable<short> TransportCountry_ID { get; set; }
        public long Item_ShortName_id { get; set; }
        public Nullable<long> ItemCategories_ID { get; set; }
        public long ID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsStationAccreditation { get; set; }
        public Nullable<bool> IsFarmAccreditation { get; set; }
        public Nullable<bool> IsCompanyAccreditation { get; set; }
        public string ConstrainText_Ar { get; set; }
        public string ConstrainText_En { get; set; }
        public string InSide_Certificate_Ar { get; set; }
        public string InSide_Certificate_En { get; set; }
        public bool IsCertificate_Addtion { get; set; }
        public string Ar_Name { get; set; }
        public string En_Name { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string ShortName_Ar { get; set; }
        public string ShortName_En { get; set; }
    }
}
