//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CertificatesRequestsLotData
    {
        public long ID { get; set; }
        public Nullable<long> PlantCertificatesRequestsID { get; set; }
        public Nullable<long> LotID { get; set; }
        public Nullable<long> Item_ShortName_ID { get; set; }
        public Nullable<bool> ISAccepted { get; set; }
        public Nullable<long> Ex_CheckRequset_Shipping_MethodID { get; set; }
    
        public virtual Ex_CertificatesRequests Ex_CertificatesRequests { get; set; }
        public virtual Ex_CheckRequset_Shipping_Method Ex_CheckRequset_Shipping_Method { get; set; }
    }
}
