//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CertificatesNewCountry
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<long> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<int> NewCountryId { get; set; }
        public Nullable<bool> ISAccepted { get; set; }
        public Nullable<int> OldCountryID { get; set; }
        public Nullable<long> Ex_CheckRequest_ID { get; set; }
        public Nullable<int> Port_International_ID_new { get; set; }
        public Nullable<int> Port_International_ID_old { get; set; }
        public Nullable<int> ReqPortType_ID { get; set; }
        public Nullable<int> Port_Type_ID_Old { get; set; }
        public Nullable<int> Port_Type_ID_New { get; set; }
    
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
    }
}
