//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest_Organization_Distribution
    {
        public long ID { get; set; }
        public long Ex_CheckRequest_ID { get; set; }
        public long Organization_ID { get; set; }
        public int Organization_Type_Id { get; set; }
        public Nullable<double> Quantity_Ton { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<long> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<long> User_Updation_Id { get; set; }
    
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
    }
}
