//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CountryConstrain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_CountryConstrain()
        {
            this.Ex_CountryConstrain_Treatment = new HashSet<Ex_CountryConstrain_Treatment>();
            this.Ex_CountryConstrain_AnalysisLabType = new HashSet<Ex_CountryConstrain_AnalysisLabType>();
            this.Ex_CountryConstrain_ArrivalPort = new HashSet<Ex_CountryConstrain_ArrivalPort>();
            this.Ex_CountryConstrain_Text = new HashSet<Ex_CountryConstrain_Text>();
        }
    
        public long ID { get; set; }
        public Nullable<short> Import_Country_ID { get; set; }
        public Nullable<short> TransportCountry_ID { get; set; }
        public long Item_ShortName_id { get; set; }
        public Nullable<long> ItemCategories_ID { get; set; }
        public Nullable<bool> IsStationAccreditation { get; set; }
        public Nullable<bool> IsFarmAccreditation { get; set; }
        public Nullable<bool> IsCompanyAccreditation { get; set; }
        public bool IsActive { get; set; }
        public long User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<long> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<long> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CountryConstrain_Treatment> Ex_CountryConstrain_Treatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CountryConstrain_AnalysisLabType> Ex_CountryConstrain_AnalysisLabType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CountryConstrain_ArrivalPort> Ex_CountryConstrain_ArrivalPort { get; set; }
        public virtual Item_ShortName Item_ShortName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CountryConstrain_Text> Ex_CountryConstrain_Text { get; set; }
    }
}
