//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequestData_Extra
    {
        public long ID { get; set; }
        public long Ex_CheckRequest_Data_ID { get; set; }
        public string ImportCompany { get; set; }
        public string ImporeterCompanyAddress { get; set; }
        public string Reciever_Name { get; set; }
        public string OwnerName { get; set; }
        public string OwnerAddress { get; set; }
        public string ImportCompany_EN { get; set; }
        public string ImporeterCompanyAddress_EN { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Ex_CheckRequest_Data Ex_CheckRequest_Data { get; set; }
    }
}
