//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_CheckRequest_Items()
        {
            this.Ex_CheckRequest_Items_Lot_Category = new HashSet<Ex_CheckRequest_Items_Lot_Category>();
        }
    
        public long ID { get; set; }
        public Nullable<int> SubPart_id { get; set; }
        public Nullable<short> Package_Material_ID { get; set; }
        public Nullable<short> Package_Type_ID { get; set; }
        public Nullable<int> Package_Count { get; set; }
        public Nullable<decimal> Package_Weight { get; set; }
        public Nullable<int> Units_Number { get; set; }
        public Nullable<bool> Is_LotDivision { get; set; }
        public Nullable<double> Size { get; set; }
        public string Order_Text { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public bool IsAccepted { get; set; }
        public Nullable<System.DateTime> Accept_Date { get; set; }
        public Nullable<System.DateTime> Accept_User_Updation_Date { get; set; }
        public Nullable<short> Accept_User_Creation_Id { get; set; }
        public Nullable<System.DateTime> Accept_User_Creation_Date { get; set; }
        public Nullable<short> Accept_User_Updation_Id { get; set; }
        public Nullable<short> Country_ID { get; set; }
        public Nullable<decimal> Net_Weight { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<long> Item_ShortName_ID { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<long> ItemCategory_ID { get; set; }
        public Nullable<long> Ex_CheckRequest_ID { get; set; }
        public Nullable<long> FarmsData_ID { get; set; }
        public Nullable<short> Governate_ID { get; set; }
        public Nullable<short> Center_ID { get; set; }
        public Nullable<short> Village_ID { get; set; }
        public string Agriculture_Hand { get; set; }
        public string Item_Permission_Number { get; set; }
        public Nullable<long> ItemCategories_Group_ID { get; set; }
        public Nullable<decimal> Net_WeightOld { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Items_Lot_Category> Ex_CheckRequest_Items_Lot_Category { get; set; }
        public virtual FarmsData FarmsData { get; set; }
        public virtual Governate Governate { get; set; }
        public virtual Item_ShortName Item_ShortName { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemCategories_Group ItemCategories_Group { get; set; }
        public virtual Village Village { get; set; }
    }
}
