//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest_Organization_Distribution_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_CheckRequest_Organization_Distribution_Master()
        {
            this.Ex_CheckRequest_Organization_Distribution_Detials = new HashSet<Ex_CheckRequest_Organization_Distribution_Detials>();
        }
    
        public long ID { get; set; }
        public long Organization_ID { get; set; }
        public int Organization_Type_Id { get; set; }
        public long Item_ID { get; set; }
        public long Item_ShortName_ID { get; set; }
        public double Totall_Quantity_Ton_Ex_CheckRequest { get; set; }
        public bool IsActive { get; set; }
        public long User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<long> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<long> User_Updation_Id { get; set; }
        public Nullable<double> Registered_Quantity_Ton_Ex_CheckRequest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Organization_Distribution_Detials> Ex_CheckRequest_Organization_Distribution_Detials { get; set; }
        public virtual Item_ShortName Item_ShortName { get; set; }
    }
}
