//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_Choose_Treatment
    {
        public long ID { get; set; }
        public Nullable<long> Ex_CheckRequest_ID { get; set; }
        public Nullable<byte> TreatmentMethods_ID { get; set; }
        public long Item_ShortName_id { get; set; }
        public bool IS_Optional { get; set; }
        public Nullable<long> Ex_CountryConstrain_Treatment_id { get; set; }
    
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        public virtual Ex_CountryConstrain_Treatment Ex_CountryConstrain_Treatment { get; set; }
        public virtual TreatmentMethod TreatmentMethod { get; set; }
    }
}
