//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CertificateAddtion
    {
        public long ID { get; set; }
        public Nullable<long> PlantCertificatesRequestsID { get; set; }
        public string Certificate_AddtionOriginal { get; set; }
        public string Certificate_AddtionOriginalUpdate { get; set; }
        public Nullable<long> ConstrainID { get; set; }
        public Nullable<long> AdminID { get; set; }
        public string Certificate_AddtionUpdateAdmin { get; set; }
        public Nullable<bool> ISAccepted { get; set; }
        public Nullable<System.DateTime> Date_Accepted { get; set; }
    
        public virtual Ex_CertificatesRequests Ex_CertificatesRequests { get; set; }
    }
}
