//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CountryConstrain_AnalysisLabType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_CountryConstrain_AnalysisLabType()
        {
            this.EX_Choose_SampleData = new HashSet<EX_Choose_SampleData>();
        }
    
        public long ID { get; set; }
        public long CountryConstrain_ID { get; set; }
        public bool IsAcive { get; set; }
        public long User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<long> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<long> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<long> Parent_ID { get; set; }
        public int AnalysisTypeID { get; set; }
    
        public virtual AnalysisType AnalysisType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EX_Choose_SampleData> EX_Choose_SampleData { get; set; }
        public virtual Ex_CountryConstrain Ex_CountryConstrain { get; set; }
    }
}
