//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_CheckRequest()
        {
            this.Ex_CertificatesNewCountry = new HashSet<Ex_CertificatesNewCountry>();
            this.Ex_CertificatesRequests = new HashSet<Ex_CertificatesRequests>();
            this.Ex_CheckRequest_Customs_Message = new HashSet<Ex_CheckRequest_Customs_Message>();
            this.Ex_CheckRequest_Data = new HashSet<Ex_CheckRequest_Data>();
            this.Ex_CheckRequest_Fees = new HashSet<Ex_CheckRequest_Fees>();
            this.Ex_CheckRequest_Items = new HashSet<Ex_CheckRequest_Items>();
            this.Ex_CheckRequest_Final_Result = new HashSet<Ex_CheckRequest_Final_Result>();
            this.Ex_CheckRequest_Visa = new HashSet<Ex_CheckRequest_Visa>();
            this.Ex_CheckRequest_Organization_Distribution_Detials = new HashSet<Ex_CheckRequest_Organization_Distribution_Detials>();
            this.Ex_CheckRequest_Organization_Distribution = new HashSet<Ex_CheckRequest_Organization_Distribution>();
            this.Ex_CheckRequest_Places = new HashSet<Ex_CheckRequest_Places>();
            this.Ex_CheckRequest_RefuseReason = new HashSet<Ex_CheckRequest_RefuseReason>();
            this.EX_Choose_SampleData = new HashSet<EX_Choose_SampleData>();
            this.EX_Choose_Treatment = new HashSet<EX_Choose_Treatment>();
            this.Ex_RequestCommittee = new HashSet<Ex_RequestCommittee>();
            this.Pallet_Data_Ex_CheckRequest_Distribution = new HashSet<Pallet_Data_Ex_CheckRequest_Distribution>();
            this.Pallet_Data_Organization__Distribution = new HashSet<Pallet_Data_Organization__Distribution>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Outlet_ID { get; set; }
        public string CheckRequest_Number { get; set; }
        public string ExportCompany { get; set; }
        public string ExportCompanyAddress { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<int> User_Type_ID { get; set; }
        public Nullable<long> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<long> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<long> User_Updation_Id { get; set; }
        public Nullable<short> IsStatus { get; set; }
        public Nullable<System.DateTime> IsAccepted_Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string NationalIDCompanyOwner { get; set; }
        public Nullable<byte> Ex_OpertaionType_ID { get; set; }
        public string Notes_Reject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CertificatesNewCountry> Ex_CertificatesNewCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CertificatesRequests> Ex_CertificatesRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Customs_Message> Ex_CheckRequest_Customs_Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Data> Ex_CheckRequest_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Fees> Ex_CheckRequest_Fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Items> Ex_CheckRequest_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Final_Result> Ex_CheckRequest_Final_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Visa> Ex_CheckRequest_Visa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Organization_Distribution_Detials> Ex_CheckRequest_Organization_Distribution_Detials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Organization_Distribution> Ex_CheckRequest_Organization_Distribution { get; set; }
        public virtual Outlet Outlet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Places> Ex_CheckRequest_Places { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_RefuseReason> Ex_CheckRequest_RefuseReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EX_Choose_SampleData> EX_Choose_SampleData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EX_Choose_Treatment> EX_Choose_Treatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_RequestCommittee> Ex_RequestCommittee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pallet_Data_Ex_CheckRequest_Distribution> Pallet_Data_Ex_CheckRequest_Distribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pallet_Data_Organization__Distribution> Pallet_Data_Organization__Distribution { get; set; }
    }
}
