//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CertificatesRequestsPaymentsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_CertificatesRequestsPaymentsType()
        {
            this.Ex_CertificatesRequestsPayments = new HashSet<Ex_CertificatesRequestsPayments>();
        }
    
        public byte ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CertificatesRequestsPayments> Ex_CertificatesRequestsPayments { get; set; }
    }
}
