//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CheckRequest_Fees
    {
        public long ID { get; set; }
        public long Ex_CheckRequest_ID { get; set; }
        public Nullable<decimal> Total_GrossWeight { get; set; }
        public Nullable<decimal> Fee_Value { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<bool> is_Fee_Rounding { get; set; }
    
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
    }
}
