//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_CertificatesRequestsFiles
    {
        public long ID { get; set; }
        public long PlantCertificatesRequestsID { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<long> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> A_AttachmentTableTypeID { get; set; }
    
        public virtual A_AttachmentTableType A_AttachmentTableType { get; set; }
        public virtual Ex_CertificatesRequests Ex_CertificatesRequests { get; set; }
    }
}
