//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_List2
    {
        public Nullable<long> Outlet_User_ID { get; set; }
        public string Outlet_User_Name { get; set; }
        public Nullable<short> Center_ID { get; set; }
        public long Ex_CheckRequest_ID { get; set; }
        public string ImCheckRequest_Number { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public short ExportCountryID { get; set; }
        public string ExportCountryName { get; set; }
        public long Importer_ID { get; set; }
        public int ImporterType_Id { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<long> Outlet_ID { get; set; }
        public string ImporterTypeName { get; set; }
        public string ImporterName { get; set; }
        public Nullable<short> f { get; set; }
        public long g { get; set; }
        public Nullable<long> Outlet_Examination_ID { get; set; }
        public string Outlet_Examination_Name { get; set; }
        public Nullable<long> Station_Examination_ID { get; set; }
        public Nullable<long> Outlet_Genshi_ID { get; set; }
        public string Outlet_Genshi_Name { get; set; }
        public Nullable<long> Station_Genshi_ID { get; set; }
        public Nullable<int> Closed_Request { get; set; }
        public int Final_Result_ID { get; set; }
        public string Final_Result_Name { get; set; }
        public string Station_Examination_Name { get; set; }
        public string Station_Genshi_Name { get; set; }
    }
}
