//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Request_TreatmentData_Confirm
    {
        public long ID { get; set; }
        public long Ex_Request_TreatmentData_ID { get; set; }
        public System.DateTime Date { get; set; }
        public long EmployeeId { get; set; }
        public string Notes { get; set; }
        public bool IsAccepted { get; set; }
    
        public virtual Ex_Request_TreatmentData Ex_Request_TreatmentData { get; set; }
    }
}
