//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_RequestCommittee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ex_RequestCommittee()
        {
            this.Ex_CheckRequest_SampleData = new HashSet<Ex_CheckRequest_SampleData>();
            this.Ex_CommitteeResult = new HashSet<Ex_CommitteeResult>();
            this.Ex_Request_TreatmentData = new HashSet<Ex_Request_TreatmentData>();
            this.Ex_RequestCommittee_Fees_ENG = new HashSet<Ex_RequestCommittee_Fees_ENG>();
            this.Ex_RequestCommittee_Shift = new HashSet<Ex_RequestCommittee_Shift>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ExCheckRequest_ID { get; set; }
        public Nullable<byte> CommitteeType_ID { get; set; }
        public Nullable<byte> ExCommitteeCheckLocation_ID { get; set; }
        public Nullable<System.DateTime> Delegation_Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<bool> IsFinishedAll { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<bool> IsAgreeResult { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> Is_Start_Android { get; set; }
        public Nullable<byte> Is_Cancel { get; set; }
    
        public virtual CommitteeType CommitteeType { get; set; }
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_SampleData> Ex_CheckRequest_SampleData { get; set; }
        public virtual Ex_CommitteeCheckLocation Ex_CommitteeCheckLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CommitteeResult> Ex_CommitteeResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_Request_TreatmentData> Ex_Request_TreatmentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_RequestCommittee_Fees_ENG> Ex_RequestCommittee_Fees_ENG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_RequestCommittee_Shift> Ex_RequestCommittee_Shift { get; set; }
    }
}
