//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm_Committee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm_Committee()
        {
            this.Farm_Committee_CheckList = new HashSet<Farm_Committee_CheckList>();
            this.Farm_Committee_Constrain = new HashSet<Farm_Committee_Constrain>();
            this.Farm_Committee_Examination = new HashSet<Farm_Committee_Examination>();
            this.Farm_Committee_Final_Result = new HashSet<Farm_Committee_Final_Result>();
            this.Farm_Committee_Shift = new HashSet<Farm_Committee_Shift>();
            this.Farm_SampleData = new HashSet<Farm_SampleData>();
            this.Farm_SampleData_Item = new HashSet<Farm_SampleData_Item>();
        }
    
        public long ID { get; set; }
        public long Farm_Request_ID { get; set; }
        public Nullable<byte> CommitteeType_ID { get; set; }
        public Nullable<byte> analysis_count { get; set; }
        public Nullable<System.DateTime> Delegation_Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsFinishedAll { get; set; }
        public decimal Amount_Total { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<byte> ShiftTiming_ID { get; set; }
        public Nullable<bool> Is_Cancel { get; set; }
        public string Refuse_Reason_Nots { get; set; }
        public Nullable<bool> Is_Start_Android { get; set; }
    
        public virtual CommitteeType CommitteeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Committee_CheckList> Farm_Committee_CheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Committee_Constrain> Farm_Committee_Constrain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Committee_Examination> Farm_Committee_Examination { get; set; }
        public virtual Farm_Request Farm_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Committee_Final_Result> Farm_Committee_Final_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Committee_Shift> Farm_Committee_Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_SampleData> Farm_SampleData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_SampleData_Item> Farm_SampleData_Item { get; set; }
    }
}
