//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm_Committee_Examination_Confirm
    {
        public long ID { get; set; }
        public long Farm_Committee_Exmination_ID { get; set; }
        public System.DateTime Date { get; set; }
        public short EmployeeId { get; set; }
        public string Notes { get; set; }
        public bool IsAccepted { get; set; }
    
        public virtual Farm_Committee_Examination Farm_Committee_Examination { get; set; }
    }
}
