//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm_Constrain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm_Constrain()
        {
            this.Farm_Committee_Constrain = new HashSet<Farm_Committee_Constrain>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Item_ID { get; set; }
        public Nullable<short> Country_Id { get; set; }
        public Nullable<long> Farm_Constrain_Text_ID { get; set; }
        public Nullable<bool> Is_Preview { get; set; }
        public Nullable<int> AnalysisType_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<byte> Count_Visit { get; set; }
    
        public virtual AnalysisType AnalysisType { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Committee_Constrain> Farm_Committee_Constrain { get; set; }
        public virtual Farm_Constrain_Text Farm_Constrain_Text { get; set; }
        public virtual Item Item { get; set; }
    }
}
