//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm_Request_ItemCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm_Request_ItemCategories()
        {
            this.Farm_Committee_Examination = new HashSet<Farm_Committee_Examination>();
            this.Farm_SampleData = new HashSet<Farm_SampleData>();
            this.Farm_SampleData_Item = new HashSet<Farm_SampleData_Item>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Farm_Request_ID { get; set; }
        public Nullable<long> Farm_ItemCategories_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<System.DateTime> Admin_Date { get; set; }
        public Nullable<short> Admin_User { get; set; }
        public Nullable<double> Area_Acres_Quarant { get; set; }
        public Nullable<double> Quantity_Ton__Quarant { get; set; }
        public Nullable<double> Quantity_Ton__Export { get; set; }
        public Nullable<double> Area_Acres { get; set; }
        public Nullable<double> Quantity_Ton { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Committee_Examination> Farm_Committee_Examination { get; set; }
        public virtual Farm_ItemCategories Farm_ItemCategories { get; set; }
        public virtual Farm_Request Farm_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_SampleData> Farm_SampleData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_SampleData_Item> Farm_SampleData_Item { get; set; }
    }
}
