//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm_Committee_Examination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm_Committee_Examination()
        {
            this.Farm_Committee_Examination_Confirm = new HashSet<Farm_Committee_Examination_Confirm>();
        }
    
        public long ID { get; set; }
        public long FarmCommittee_ID { get; set; }
        public Nullable<long> Farm_Request_ItemCategories_ID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<double> Quantity_Ton { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public short User_Creation_Id { get; set; }
        public Nullable<bool> IsAdminFinalResult { get; set; }
        public string AdminFinalResult_Note { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<bool> Admin_Confirmation { get; set; }
        public Nullable<short> Admin_User { get; set; }
        public Nullable<System.DateTime> Admin_Date { get; set; }
        public Nullable<double> Area_Acres { get; set; }
    
        public virtual Farm_Committee Farm_Committee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Committee_Examination_Confirm> Farm_Committee_Examination_Confirm { get; set; }
        public virtual Farm_Request_ItemCategories Farm_Request_ItemCategories { get; set; }
    }
}
