//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmsData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FarmsData()
        {
            this.Ex_CheckRequest_Items = new HashSet<Ex_CheckRequest_Items>();
            this.Farm_Company = new HashSet<Farm_Company>();
            this.Farm_ItemCategories = new HashSet<Farm_ItemCategories>();
            this.Farm_Request = new HashSet<Farm_Request>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Item_ID { get; set; }
        public string FarmCode_14 { get; set; }
        public Nullable<short> Village_ID { get; set; }
        public string Name_Ar { get; set; }
        public string Name_En { get; set; }
        public string Address_Ar { get; set; }
        public string Address_En { get; set; }
        public string ThePivot { get; set; }
        public string GPSRead { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IS_OnlineOffline { get; set; }
        public string FileUpload { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> Center_Id { get; set; }
        public Nullable<short> Govern_ID { get; set; }
    
        public virtual Center Center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Items> Ex_CheckRequest_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Company> Farm_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_ItemCategories> Farm_ItemCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Request> Farm_Request { get; set; }
        public virtual Governate Governate { get; set; }
        public virtual Item Item { get; set; }
        public virtual Village Village { get; set; }
    }
}
