//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm_Committee_CheckList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm_Committee_CheckList()
        {
            this.Farm_Committee_CheckList_Confirm = new HashSet<Farm_Committee_CheckList_Confirm>();
        }
    
        public long ID { get; set; }
        public long FarmCommittee_ID { get; set; }
        public long Farm_Country_CheckList_ID { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string Notes_Ar { get; set; }
        public string Notes_En { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<bool> IsAccepted_Quarantine { get; set; }
        public Nullable<long> EmployeeId_Quarantine { get; set; }
    
        public virtual Farm_Committee Farm_Committee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Committee_CheckList_Confirm> Farm_Committee_CheckList_Confirm { get; set; }
        public virtual Farm_Country_CheckList Farm_Country_CheckList { get; set; }
    }
}
