//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fees_Transactions_Detiles
    {
        public long ID { get; set; }
        public Nullable<long> Fees_Action_ID { get; set; }
        public Nullable<long> Fees_Transactions_ID { get; set; }
        public Nullable<long> Items_ID { get; set; }
        public Nullable<long> Shift_ID { get; set; }
        public Nullable<long> SampleData_ID { get; set; }
        public Nullable<long> TreatmentData_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
    
        public virtual Fees_Action Fees_Action { get; set; }
        public virtual Fees_Transactions Fees_Transactions { get; set; }
    }
}
