//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fees_Transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fees_Transactions()
        {
            this.Fees_Transactions_Detiles = new HashSet<Fees_Transactions_Detiles>();
            this.Fees_Transactions_Payment_Detiles = new HashSet<Fees_Transactions_Payment_Detiles>();
        }
    
        public long ID { get; set; }
        public Nullable<short> TableName_ID { get; set; }
        public Nullable<long> Table_ID { get; set; }
        public Nullable<decimal> Amount_Total { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<bool> IsSuccess_Bank { get; set; }
        public string Code_Bank { get; set; }
        public Nullable<int> User_Type_ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> Account_Type { get; set; }
    
        public virtual Fees_TableName Fees_TableName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fees_Transactions_Detiles> Fees_Transactions_Detiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fees_Transactions_Payment_Detiles> Fees_Transactions_Payment_Detiles { get; set; }
    }
}
