//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fees_Certificates_Payment_Detiles
    {
        public long ID { get; set; }
        public string AttachmentPath { get; set; }
        public string CardOrGroupNumber { get; set; }
        public string ReferenceOrCouponNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<long> pos_information_id { get; set; }
        public Nullable<long> Ex_CertificatesRequests_ID { get; set; }
    
        public virtual Ex_CertificatesRequests Ex_CertificatesRequests { get; set; }
    }
}
