//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_CountryConstrain_ArrivalPort
    {
        public long Id { get; set; }
        public Nullable<int> Port_National_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public long User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<long> User_Deletion_Id { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> Item_ShortName_ID { get; set; }
        public byte Port_Type_ID { get; set; }
        public Nullable<short> Id_QualitativeGroup { get; set; }
    
        public virtual Item_ShortName Item_ShortName { get; set; }
        public virtual PortNational PortNational { get; set; }
        public virtual QualitativeGroup QualitativeGroup { get; set; }
    }
}
