//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_choose_Constrain_
    {
        public long ID { get; set; }
        public Nullable<byte> Im_Constrain_Type_Id { get; set; }
        public Nullable<long> Im_Constrains_Special_Id { get; set; }
        public Nullable<long> Im_Constrain_Initiator_Text_Id { get; set; }
    
        public virtual Im_Constrain_Initiator_Text Im_Constrain_Initiator_Text { get; set; }
        public virtual Im_Constrain_Type Im_Constrain_Type { get; set; }
        public virtual Im_Constrains_Special Im_Constrains_Special { get; set; }
    }
}
