//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_CommitteeResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_CommitteeResult()
        {
            this.A_AttachmentData_Im_CommitteeResult_Infection = new HashSet<A_AttachmentData_Im_CommitteeResult_Infection>();
            this.Im_CommitteeResult_Confirm = new HashSet<Im_CommitteeResult_Confirm>();
            this.Im_CommitteeResult_Infection = new HashSet<Im_CommitteeResult_Infection>();
        }
    
        public long ID { get; set; }
        public long Committee_ID { get; set; }
        public long Im_Request_Item_Id { get; set; }
        public Nullable<long> LotData_ID { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<byte> CommitteeResultType_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsAdminResult { get; set; }
        public string AdminFinalResult_Note { get; set; }
        public Nullable<double> QuantitySize { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IS_Total { get; set; }
        public Nullable<long> Item_ShortName_ID { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<bool> IS_Total_Android { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_AttachmentData_Im_CommitteeResult_Infection> A_AttachmentData_Im_CommitteeResult_Infection { get; set; }
        public virtual CommitteeResultType CommitteeResultType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CommitteeResult_Confirm> Im_CommitteeResult_Confirm { get; set; }
        public virtual Im_RequestCommittee Im_RequestCommittee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CommitteeResult_Infection> Im_CommitteeResult_Infection { get; set; }
        public virtual Item_ShortName Item_ShortName { get; set; }
    }
}
