//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_CheckRequest_Distribution
    {
        public long ID { get; set; }
        public Nullable<long> Im_CheckRequest_ID { get; set; }
        public Nullable<long> Item_ID { get; set; }
        public Nullable<long> Item_ShortName_ID { get; set; }
        public Nullable<long> Im_Initiator_ID { get; set; }
        public Nullable<long> ItemCategory_ID { get; set; }
        public int ImporterType_Id { get; set; }
        public long Importer_ID { get; set; }
        public Nullable<System.DateTime> Date_Distribution { get; set; }
        public Nullable<byte> Num_Distribution { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> Net_Weight { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
    
        public virtual Im_CheckRequest Im_CheckRequest { get; set; }
    }
}
