//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_Constrain_Initiator_Text
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_Constrain_Initiator_Text()
        {
            this.Im_choose_Constrain_ = new HashSet<Im_choose_Constrain_>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ConstrainText_ID { get; set; }
        public Nullable<long> Im_Initiator_ID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsAcceppted { get; set; }
        public bool IsActive1 { get; set; }
        public long User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<long> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<long> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<byte> Group_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_choose_Constrain_> Im_choose_Constrain_ { get; set; }
        public virtual Im_CountryConstrain_Text Im_CountryConstrain_Text { get; set; }
        public virtual Im_Initiator Im_Initiator { get; set; }
    }
}
