//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_CustodyPlace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_CustodyPlace()
        {
            this.Im_CustodyPlace_CheckRequest = new HashSet<Im_CustodyPlace_CheckRequest>();
        }
    
        public long ID { get; set; }
        public string En_Desc { get; set; }
        public string Ar_Desc { get; set; }
        public double Storage_capacity { get; set; }
        public short Center_Id { get; set; }
        public string Address { get; set; }
        public string Owner_Name { get; set; }
        public string NationalID { get; set; }
        public string Phone { get; set; }
        public double PreviewQuantityDuration { get; set; }
        public Nullable<System.DateTime> DateStored { get; set; }
        public double Quantity { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> Status { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public byte Im_CustodyPlaceType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CustodyPlace_CheckRequest> Im_CustodyPlace_CheckRequest { get; set; }
        public virtual Im_CustodyPlaceType Im_CustodyPlaceType1 { get; set; }
    }
}
