//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_CheckRequest_Manafest
    {
        public long ID { get; set; }
        public long Im_CheckRequest_Id { get; set; }
        public long Im_Manafest { get; set; }
    
        public virtual Im_CheckRequest Im_CheckRequest { get; set; }
        public virtual Im_Manafest Im_Manafest1 { get; set; }
    }
}
