//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_CheckRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_CheckRequest()
        {
            this.Im_CheckRequest_Customs_Message = new HashSet<Im_CheckRequest_Customs_Message>();
            this.Im_CheckRequest_Data = new HashSet<Im_CheckRequest_Data>();
            this.Im_CheckRequest_Distribution = new HashSet<Im_CheckRequest_Distribution>();
            this.Im_CheckRequest_Final_Result = new HashSet<Im_CheckRequest_Final_Result>();
            this.Im_CheckRequest_Visa = new HashSet<Im_CheckRequest_Visa>();
            this.Im_CheckRequest_Manafest = new HashSet<Im_CheckRequest_Manafest>();
            this.Im_CheckRequest_RefuseReason = new HashSet<Im_CheckRequest_RefuseReason>();
            this.Im_CheckRequset_Shipping_Method = new HashSet<Im_CheckRequset_Shipping_Method>();
            this.Im_CustodyPlace_CheckRequest = new HashSet<Im_CustodyPlace_CheckRequest>();
            this.Im_PermissionRequest = new HashSet<Im_PermissionRequest>();
            this.Im_RequestCommittee = new HashSet<Im_RequestCommittee>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Outlet_ID { get; set; }
        public string CheckRequest_Number { get; set; }
        public string ExportCompany { get; set; }
        public string ExportCompanyAddress { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<System.DateTime> IsAccepted_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<byte> Im_OperationType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_Customs_Message> Im_CheckRequest_Customs_Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_Data> Im_CheckRequest_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_Distribution> Im_CheckRequest_Distribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_Final_Result> Im_CheckRequest_Final_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_Visa> Im_CheckRequest_Visa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_Manafest> Im_CheckRequest_Manafest { get; set; }
        public virtual Outlet Outlet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_RefuseReason> Im_CheckRequest_RefuseReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequset_Shipping_Method> Im_CheckRequset_Shipping_Method { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CustodyPlace_CheckRequest> Im_CustodyPlace_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionRequest> Im_PermissionRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_RequestCommittee> Im_RequestCommittee { get; set; }
    }
}
