//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_CheckRequest_SampleData_Confirm
    {
        public long ID { get; set; }
        public long Im_CheckRequest_SampleData_ID { get; set; }
        public System.DateTime Date { get; set; }
        public short EmployeeId { get; set; }
        public string Notes { get; set; }
        public bool IsAccepted { get; set; }
    
        public virtual Im_CheckRequest_SampleData Im_CheckRequest_SampleData { get; set; }
    }
}
