//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_CustodyPlace_CheckRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_CustodyPlace_CheckRequest()
        {
            this.Im_Committee_CustodyPlace = new HashSet<Im_Committee_CustodyPlace>();
            this.Im_PermissionItem_Division_Custody = new HashSet<Im_PermissionItem_Division_Custody>();
        }
    
        public long ID { get; set; }
        public long Im_CheckRequest_ID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> Status { get; set; }
        public long User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<long> Im_CustodyPlace_ID { get; set; }
        public Nullable<long> Station_ID { get; set; }
    
        public virtual Im_CheckRequest Im_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_Committee_CustodyPlace> Im_Committee_CustodyPlace { get; set; }
        public virtual Im_CustodyPlace Im_CustodyPlace { get; set; }
        public virtual Station Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionItem_Division_Custody> Im_PermissionItem_Division_Custody { get; set; }
    }
}
