//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_Execution_Items
    {
        public long ID { get; set; }
        public long Im_Execution_Id { get; set; }
        public long Im_CheckRequest_Item_ID { get; set; }
        public decimal GrossWeight { get; set; }
        public Nullable<long> Im_CheckRequest_Items_Lot_Category_ID { get; set; }
    
        public virtual Im_CheckRequest_Items Im_CheckRequest_Items { get; set; }
        public virtual Im_CheckRequest_Items_Lot_Category Im_CheckRequest_Items_Lot_Category { get; set; }
        public virtual Im_Execution Im_Execution { get; set; }
    }
}
