//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_Execution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_Execution()
        {
            this.Im_Execution_Items = new HashSet<Im_Execution_Items>();
        }
    
        public long ID { get; set; }
        public long Im_RequestCommittee_Id { get; set; }
        public string Execution_Place { get; set; }
        public string Execution_Method { get; set; }
        public byte[] Execution_File { get; set; }
    
        public virtual Im_RequestCommittee Im_RequestCommittee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_Execution_Items> Im_Execution_Items { get; set; }
    }
}
