//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_Initiator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_Initiator()
        {
            this.Im_CheckRequest_Items = new HashSet<Im_CheckRequest_Items>();
            this.Im_Constrain_Initiator_Text = new HashSet<Im_Constrain_Initiator_Text>();
            this.Im_PermissionItems = new HashSet<Im_PermissionItems>();
        }
    
        public long ID { get; set; }
        public Nullable<short> Country_Id { get; set; }
        public Nullable<long> Item_ShortName_ID { get; set; }
        public Nullable<short> QualitativeGroup_Id { get; set; }
        public int Initiator_Status { get; set; }
        public bool IsActive { get; set; }
        public string ForbiddenReason { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public string AttachmentPath { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_Items> Im_CheckRequest_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_Constrain_Initiator_Text> Im_Constrain_Initiator_Text { get; set; }
        public virtual Item_ShortName Item_ShortName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionItems> Im_PermissionItems { get; set; }
    }
}
