//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_Manafest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_Manafest()
        {
            this.Im_CheckRequest_Manafest = new HashSet<Im_CheckRequest_Manafest>();
        }
    
        public long ID { get; set; }
        public string Manafest_Num { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string ShipName { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public Nullable<System.TimeSpan> ArriveTime { get; set; }
        public string NavigationCompany { get; set; }
        public string Origin { get; set; }
        public string ShipmentPort { get; set; }
        public string PolicyNumber { get; set; }
        public string ImporterName { get; set; }
        public string PlantName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> Net_Weight { get; set; }
        public string EditRecord { get; set; }
        public Nullable<System.DateTime> DischargeEndDate { get; set; }
        public Nullable<System.DateTime> ToHagrDate { get; set; }
        public Nullable<System.DateTime> ExaminationDate { get; set; }
        public string CustomsCertificate { get; set; }
        public string CompletionApplicationNum { get; set; }
        public bool IsTransit { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_Manafest> Im_CheckRequest_Manafest { get; set; }
    }
}
