//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_PermissionItem_Division_Custody_DismissCommittee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_PermissionItem_Division_Custody_DismissCommittee()
        {
            this.Im_PermissionItem_Division_Custody_ReceiveCommittee = new HashSet<Im_PermissionItem_Division_Custody_ReceiveCommittee>();
        }
    
        public long ID { get; set; }
        public long Im_PermissionItem_Division_Custody_Id { get; set; }
        public long Im_RequestCommittee_Id { get; set; }
        public Nullable<System.DateTime> Dismiss_Date { get; set; }
        public Nullable<System.TimeSpan> DismissTime { get; set; }
        public bool IsApproved { get; set; }
        public bool Status { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public string Lock_Lead { get; set; }
        public string Notes { get; set; }
    
        public virtual Im_PermissionItem_Division_Custody Im_PermissionItem_Division_Custody { get; set; }
        public virtual Im_RequestCommittee Im_RequestCommittee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionItem_Division_Custody_ReceiveCommittee> Im_PermissionItem_Division_Custody_ReceiveCommittee { get; set; }
    }
}
