//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_PermissionItem_Division_Custody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_PermissionItem_Division_Custody()
        {
            this.Im_PermissionItem_Division_Custody_DismissCommittee = new HashSet<Im_PermissionItem_Division_Custody_DismissCommittee>();
        }
    
        public long ID { get; set; }
        public long Im_CustodyPlace_Id { get; set; }
        public long Im_CheckRequest_Item_Id { get; set; }
        public decimal GrossWeight { get; set; }
        public byte Transport_Mean_Id { get; set; }
        public string Transport_Mean_Number { get; set; }
        public string Driver_Name { get; set; }
        public string Driver_Phone { get; set; }
        public string Driver_National_Id { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<System.DateTime> Accept_Date { get; set; }
        public Nullable<System.DateTime> Accept_User_Updation_Date { get; set; }
        public Nullable<short> Accept_User_Creation_Id { get; set; }
        public Nullable<System.DateTime> Accept_User_Creation_Date { get; set; }
        public Nullable<short> Accept_User_Updation_Id { get; set; }
    
        public virtual Im_CheckRequest_Items Im_CheckRequest_Items { get; set; }
        public virtual Im_CustodyPlace_CheckRequest Im_CustodyPlace_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionItem_Division_Custody_DismissCommittee> Im_PermissionItem_Division_Custody_DismissCommittee { get; set; }
        public virtual Transport_Mean Transport_Mean { get; set; }
    }
}
