//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_PermissionItems_Category
    {
        public long ID { get; set; }
        public Nullable<long> Im_PermissionItems_ID { get; set; }
        public Nullable<long> ItemCategory_ID { get; set; }
        public Nullable<long> ItemCategoryGroup_ID { get; set; }
        public Nullable<short> Package_Material_ID { get; set; }
        public Nullable<short> Package_Type_ID { get; set; }
        public Nullable<int> Package_Count { get; set; }
        public Nullable<decimal> Package_Weight { get; set; }
        public Nullable<int> Units_Number { get; set; }
        public Nullable<double> Size { get; set; }
        public string Order_Text { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public string Reason_Entry { get; set; }
    
        public virtual Im_PermissionItems Im_PermissionItems { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemCategories_Group ItemCategories_Group { get; set; }
    }
}
