//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_PermissionRequest_RefuseReason
    {
        public long ID { get; set; }
        public long Im_PermissionRequest_Id { get; set; }
        public short Refuse_Reason_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public long User_Creation_Id { get; set; }
        public string Nots { get; set; }
        public Nullable<bool> ISActive { get; set; }
    
        public virtual Im_PermissionRequest Im_PermissionRequest { get; set; }
        public virtual Refuse_Reason Refuse_Reason { get; set; }
    }
}
