//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_PermissionRequest_History
    {
        public Nullable<long> ID { get; set; }
        public Nullable<decimal> ImPermission_Number { get; set; }
        public System.DateTime Arrival_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsAcceppted { get; set; }
        public Nullable<bool> IS_Print_Ar { get; set; }
        public Nullable<bool> IS_Print_EN { get; set; }
        public Nullable<bool> IS_Notice_Arrival { get; set; }
        public Nullable<long> Im_CheckRequest_ID { get; set; }
        public Nullable<byte> Renewal_Status { get; set; }
        public Nullable<byte> Print_Count { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
    }
}
