//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_PermissionItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_PermissionItems()
        {
            this.Im_ItemsLotDivision = new HashSet<Im_ItemsLotDivision>();
            this.Im_PermissionItems_Category = new HashSet<Im_PermissionItems_Category>();
            this.Im_SubDivission = new HashSet<Im_SubDivission>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Im_PermissionRequest_ID { get; set; }
        public Nullable<long> Im_CheckRequest_ID { get; set; }
        public Nullable<long> Im_Initiator_ID { get; set; }
        public Nullable<int> SubPart_id { get; set; }
        public string Item_Permission_Number { get; set; }
        public Nullable<short> Package_Material_ID { get; set; }
        public Nullable<short> Package_Type_ID { get; set; }
        public Nullable<int> Package_Count { get; set; }
        public Nullable<decimal> Package_Weight { get; set; }
        public Nullable<int> Units_Number { get; set; }
        public Nullable<bool> Is_LotDivision { get; set; }
        public Nullable<double> Size { get; set; }
        public string Order_Text { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public bool IsAccepted { get; set; }
        public Nullable<System.DateTime> Accept_Date { get; set; }
        public Nullable<System.DateTime> Accept_User_Updation_Date { get; set; }
        public Nullable<short> Accept_User_Creation_Id { get; set; }
        public Nullable<System.DateTime> Accept_User_Creation_Date { get; set; }
        public Nullable<short> Accept_User_Updation_Id { get; set; }
        public Nullable<short> Country_ID { get; set; }
        public Nullable<long> Item_ShortName_ID { get; set; }
        public Nullable<short> QualitativeGroup_Id { get; set; }
    
        public virtual Im_Initiator Im_Initiator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_ItemsLotDivision> Im_ItemsLotDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionItems_Category> Im_PermissionItems_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_SubDivission> Im_SubDivission { get; set; }
    }
}
