//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_RequestData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_RequestData()
        {
            this.Im_Request_Port = new HashSet<Im_Request_Port>();
            this.Im_RequestDat_Extra = new HashSet<Im_RequestDat_Extra>();
        }
    
        public long ID { get; set; }
        public Nullable<byte> Im_OperationType { get; set; }
        public long Importer_ID { get; set; }
        public int ImporterType_Id { get; set; }
        public short ExportCountry_Id { get; set; }
        public Nullable<byte> Shipment_Mean_Id { get; set; }
        public Nullable<byte> Transport_Mean_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<long> Im_PermissionRequest_ID { get; set; }
        public Nullable<long> Im_CheckRequest_ID { get; set; }
        public string Ship_Name { get; set; }
        public string DelegateName { get; set; }
        public string DelegateAddress { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_Request_Port> Im_Request_Port { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_RequestDat_Extra> Im_RequestDat_Extra { get; set; }
        public virtual Shipment_Mean Shipment_Mean { get; set; }
        public virtual Transport_Mean Transport_Mean { get; set; }
    }
}
