//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_RequestCommittee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_RequestCommittee()
        {
            this.Im_CheckRequest_SampleData = new HashSet<Im_CheckRequest_SampleData>();
            this.Im_CommitteeResult = new HashSet<Im_CommitteeResult>();
            this.Im_Execution = new HashSet<Im_Execution>();
            this.Im_PermissionItem_Division_Custody_DismissCommittee = new HashSet<Im_PermissionItem_Division_Custody_DismissCommittee>();
            this.Im_PermissionItem_Division_Custody_ReceiveCommittee = new HashSet<Im_PermissionItem_Division_Custody_ReceiveCommittee>();
            this.Im_Request_TreatmentData = new HashSet<Im_Request_TreatmentData>();
            this.Im_RequestCommittee_Procedure = new HashSet<Im_RequestCommittee_Procedure>();
            this.Im_RequestCommittee_Shift = new HashSet<Im_RequestCommittee_Shift>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ImCheckRequest_ID { get; set; }
        public Nullable<byte> CommitteeType_ID { get; set; }
        public Nullable<byte> ImCommitteeCheckLocation_ID { get; set; }
        public Nullable<System.DateTime> Delegation_Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<bool> IsFinishedAll { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<bool> IsAgreeResult { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> Is_Start_Android { get; set; }
        public Nullable<byte> Is_Cancel { get; set; }
    
        public virtual CommitteeType CommitteeType { get; set; }
        public virtual Im_CheckRequest Im_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_SampleData> Im_CheckRequest_SampleData { get; set; }
        public virtual Im_CommitteeCheckLocation Im_CommitteeCheckLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CommitteeResult> Im_CommitteeResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_Execution> Im_Execution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionItem_Division_Custody_DismissCommittee> Im_PermissionItem_Division_Custody_DismissCommittee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionItem_Division_Custody_ReceiveCommittee> Im_PermissionItem_Division_Custody_ReceiveCommittee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_Request_TreatmentData> Im_Request_TreatmentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_RequestCommittee_Procedure> Im_RequestCommittee_Procedure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_RequestCommittee_Shift> Im_RequestCommittee_Shift { get; set; }
    }
}
