//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_RequestDat_Extra
    {
        public long ID { get; set; }
        public long Im_RequestData_ID { get; set; }
        public string ImportCompany { get; set; }
        public string ImporeterCompanyAddress { get; set; }
        public string Reciever_Name { get; set; }
        public string OwnerName { get; set; }
        public string OwnerAddress { get; set; }
        public string ImportCompany_EN { get; set; }
        public string ImporeterCompanyAddress_EN { get; set; }
    
        public virtual Im_RequestData Im_RequestData { get; set; }
    }
}
