//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_ScientificResearch_ItemPlant_Product
    {
        public long ID { get; set; }
        public long Im_ScientificResearch_ID { get; set; }
        public string ProdPlant__Name { get; set; }
        public int ProductStatus_Id { get; set; }
        public string PlantPart_Name { get; set; }
        public string Scientific_Name { get; set; }
        public string Procedure_Summery { get; set; }
        public string PlantCategories { get; set; }
        public int Research_Type_Id { get; set; }
    
        public virtual A_SystemCode A_SystemCode { get; set; }
        public virtual Im_ScientificResearch Im_ScientificResearch { get; set; }
        public virtual Item_Status Item_Status { get; set; }
    }
}
