//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_ScientificResearch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Im_ScientificResearch()
        {
            this.Im_ScientificResearch_ItemPlant_Inseket_Lieble = new HashSet<Im_ScientificResearch_ItemPlant_Inseket_Lieble>();
            this.Im_ScientificResearch_ItemPlant_Product = new HashSet<Im_ScientificResearch_ItemPlant_Product>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ImPermission_ID { get; set; }
        public long Im_ScientificResearch_Person_Id { get; set; }
        public long Im_ScientificResearch_Organization_Id { get; set; }
        public string Person_Job_Title_Ar { get; set; }
        public string Org_Manager_Name_Ar { get; set; }
        public string Org_Manager_Name_En { get; set; }
        public int PortNational_Id { get; set; }
        public string Tax_Certificate_Number { get; set; }
        public string Shipment_Policy_Number { get; set; }
        public byte Shipment_Mean_Id { get; set; }
        public byte Transport_Mean_Id { get; set; }
        public short Quantity { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public string Transport_Mean_Name { get; set; }
    
        public virtual Im_PermissionRequest Im_PermissionRequest { get; set; }
        public virtual Im_ScientificResearch_Organization Im_ScientificResearch_Organization { get; set; }
        public virtual Im_ScientificResearch_Person Im_ScientificResearch_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_ScientificResearch_ItemPlant_Inseket_Lieble> Im_ScientificResearch_ItemPlant_Inseket_Lieble { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_ScientificResearch_ItemPlant_Product> Im_ScientificResearch_ItemPlant_Product { get; set; }
        public virtual PortNational PortNational { get; set; }
        public virtual Shipment_Mean Shipment_Mean { get; set; }
        public virtual Transport_Mean Transport_Mean { get; set; }
    }
}
