//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Im_SubDivission
    {
        public long ID { get; set; }
        public long Im_Item_ID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string ShipmentPolicy_Number { get; set; }
        public string Customs_Certificate { get; set; }
        public string FilePath { get; set; }
    
        public virtual Im_PermissionItems Im_PermissionItems { get; set; }
    }
}
