//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Ex_CommitteeResult_Infection = new HashSet<Ex_CommitteeResult_Infection>();
            this.Farm_Constrain = new HashSet<Farm_Constrain>();
            this.Farm_Country_CheckList = new HashSet<Farm_Country_CheckList>();
            this.FarmsDatas = new HashSet<FarmsData>();
            this.Im_CommitteeResult_Infection = new HashSet<Im_CommitteeResult_Infection>();
            this.Item_ShortName = new HashSet<Item_ShortName>();
            this.ItemCategories = new HashSet<ItemCategory>();
            this.ItemParts = new HashSet<ItemPart>();
            this.TreatmentMaterials = new HashSet<TreatmentMaterial>();
        }
    
        public long ID { get; set; }
        public string Name_Ar { get; set; }
        public string Name_En { get; set; }
        public string Scientific_Name { get; set; }
        public Nullable<int> Family_ID { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public string Descreption_Ar { get; set; }
        public string Descreption_En { get; set; }
        public string Picture { get; set; }
        public bool IsForbidden { get; set; }
        public string ForbiddenReason { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<bool> IsPermissionRequest { get; set; }
        public Nullable<byte> Item_Type_ID { get; set; }
        public Nullable<bool> Is_known_item { get; set; }
        public Nullable<bool> IsPlantInEgypt { get; set; }
        public string Item_Code { get; set; }
        public Nullable<bool> Agriculture_17 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CommitteeResult_Infection> Ex_CommitteeResult_Infection { get; set; }
        public virtual Family Family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Constrain> Farm_Constrain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Country_CheckList> Farm_Country_CheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmsData> FarmsDatas { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CommitteeResult_Infection> Im_CommitteeResult_Infection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_ShortName> Item_ShortName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCategory> ItemCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPart> ItemParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentMaterial> TreatmentMaterials { get; set; }
    }
}
