//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemCategory()
        {
            this.Ex_CheckRequest_Items = new HashSet<Ex_CheckRequest_Items>();
            this.Farm_ItemCategories = new HashSet<Farm_ItemCategories>();
            this.Im_CheckRequest_Items_Lot_Category = new HashSet<Im_CheckRequest_Items_Lot_Category>();
            this.Im_PermissionItems_Category = new HashSet<Im_PermissionItems_Category>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Item_ID { get; set; }
        public string Name_Ar { get; set; }
        public string Name_En { get; set; }
        public Nullable<long> Company_ID { get; set; }
        public Nullable<bool> IsRegister { get; set; }
        public string Register_NumDate { get; set; }
        public Nullable<System.DateTime> Register_EndDate { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public bool IsForbidden { get; set; }
        public bool CurrentStatus { get; set; }
        public string Protect_Property { get; set; }
        public string Notes { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<int> Resolution_Number { get; set; }
        public Nullable<short> ItemCategories_Type { get; set; }
        public Nullable<bool> Is_Plant_Egypt { get; set; }
        public Nullable<long> ItemCategories_Group_ID { get; set; }
        public Nullable<int> Resolution_Date { get; set; }
    
        public virtual Company_National Company_National { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Items> Ex_CheckRequest_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_ItemCategories> Farm_ItemCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_Items_Lot_Category> Im_CheckRequest_Items_Lot_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionItems_Category> Im_PermissionItems_Category { get; set; }
        public virtual Item Item { get; set; }
        public virtual ItemCategories_Group ItemCategories_Group { get; set; }
        public virtual ItemCategories_Type ItemCategories_Type1 { get; set; }
    }
}
