//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_ShortName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_ShortName()
        {
            this.CompanyAccreditations = new HashSet<CompanyAccreditation>();
            this.Ex_CheckRequest_Items = new HashSet<Ex_CheckRequest_Items>();
            this.Ex_CheckRequest_Organization_Distribution_Master = new HashSet<Ex_CheckRequest_Organization_Distribution_Master>();
            this.EX_Choose_SampleData = new HashSet<EX_Choose_SampleData>();
            this.Ex_CommitteeResult = new HashSet<Ex_CommitteeResult>();
            this.Ex_CountryConstrain = new HashSet<Ex_CountryConstrain>();
            this.Im_CommitteeResult = new HashSet<Im_CommitteeResult>();
            this.Im_CountryConstrain_ArrivalPort = new HashSet<Im_CountryConstrain_ArrivalPort>();
            this.Im_Initiator = new HashSet<Im_Initiator>();
            this.Station_Accreditation_Data_Item_ShortName = new HashSet<Station_Accreditation_Data_Item_ShortName>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Item_ID { get; set; }
        public Nullable<int> SubPart_ID { get; set; }
        public Nullable<int> Item_Status_ID { get; set; }
        public Nullable<int> Item_Purpose_ID { get; set; }
        public string ShortName_Ar { get; set; }
        public string ShortName_En { get; set; }
        public bool ExportStatus { get; set; }
        public bool ImportStatus { get; set; }
        public string Reason { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<bool> IS_ShortName { get; set; }
        public Nullable<short> QualitativeGroup_Id { get; set; }
        public Nullable<byte> Item_Type_ID { get; set; }
        public Nullable<bool> Is_ImportTaxFree { get; set; }
        public Nullable<long> Product_ID { get; set; }
        public Nullable<long> ItemCategories_Group_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyAccreditation> CompanyAccreditations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Items> Ex_CheckRequest_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Organization_Distribution_Master> Ex_CheckRequest_Organization_Distribution_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EX_Choose_SampleData> EX_Choose_SampleData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CommitteeResult> Ex_CommitteeResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CountryConstrain> Ex_CountryConstrain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CommitteeResult> Im_CommitteeResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CountryConstrain_ArrivalPort> Im_CountryConstrain_ArrivalPort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_Initiator> Im_Initiator { get; set; }
        public virtual Item Item { get; set; }
        public virtual Item_Purpose Item_Purpose { get; set; }
        public virtual QualitativeGroup QualitativeGroup { get; set; }
        public virtual SubPart SubPart { get; set; }
        public virtual Item_Status Item_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation_Data_Item_ShortName> Station_Accreditation_Data_Item_ShortName { get; set; }
    }
}
