//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiableItems_ShortName
    {
        public long ID { get; set; }
        public Nullable<int> LiableItem_ID { get; set; }
        public Nullable<int> PlantPurpose_ID { get; set; }
        public Nullable<int> LiableItems_Status_ID { get; set; }
        public Nullable<int> Biological_Phase_ID { get; set; }
        public string ScientficName_En { get; set; }
        public string ScientficName_Ar { get; set; }
        public string ShortName_Ar { get; set; }
        public string ShortName_En { get; set; }
        public string HSCODE { get; set; }
        public bool ExportStatus { get; set; }
        public bool ImportStatus { get; set; }
        public string Reason { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
    
        public virtual Biological_Phase Biological_Phase { get; set; }
        public virtual Item_Purpose Item_Purpose { get; set; }
        public virtual LiableItem LiableItem { get; set; }
        public virtual LiableItems_Status LiableItems_Status { get; set; }
    }
}
