//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet_Data_Organization__Distribution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pallet_Data_Organization__Distribution()
        {
            this.Pallet_Data_Ex_CheckRequest_Distribution = new HashSet<Pallet_Data_Ex_CheckRequest_Distribution>();
        }
    
        public long ID { get; set; }
        public long Organization_ID { get; set; }
        public int Organization_Type_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsAcceppted { get; set; }
        public long User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<long> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<long> User_Updation_Id { get; set; }
        public long Ex_CheckRequest_ID { get; set; }
    
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pallet_Data_Ex_CheckRequest_Distribution> Pallet_Data_Ex_CheckRequest_Distribution { get; set; }
    }
}
