//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet_Data_Ex_CheckRequest_Distribution
    {
        public long ID { get; set; }
        public long Ex_CheckRequest_ID { get; set; }
        public Nullable<long> Pallet_Data_Organization__Distribution_ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
    
        public virtual Ex_CheckRequest Ex_CheckRequest { get; set; }
        public virtual Pallet_Data_Organization__Distribution Pallet_Data_Organization__Distribution { get; set; }
    }
}
