//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Person_IDType { get; set; }
        public string IDNumber { get; set; }
        public Nullable<short> Country_ID { get; set; }
        public string Job { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> User_Activation_Id { get; set; }
        public Nullable<System.DateTime> User_Activation_Date { get; set; }
        public Nullable<short> Village_ID { get; set; }
        public Nullable<short> Center_ID { get; set; }
        public Nullable<short> Govern_ID { get; set; }
        public string Name_EN { get; set; }
        public string Address_EN { get; set; }
    
        public virtual A_SystemCode A_SystemCode { get; set; }
        public virtual Country Country { get; set; }
    }
}
