//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pos_information()
        {
            this.Fees_Transactions_Payment_Detiles = new HashSet<Fees_Transactions_Payment_Detiles>();
        }
    
        public long Id { get; set; }
        public string pos_number { get; set; }
        public Nullable<long> user_id { get; set; }
        public string place { get; set; }
        public Nullable<long> Outlet_ID { get; set; }
        public Nullable<int> InstitutionalCode { get; set; }
        public string BankAccount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fees_Transactions_Payment_Detiles> Fees_Transactions_Payment_Detiles { get; set; }
        public virtual Outlet Outlet { get; set; }
        public virtual pos_information pos_information1 { get; set; }
        public virtual pos_information pos_information2 { get; set; }
    }
}
