//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Public_Organization
    {
        public long ID { get; set; }
        public string Name_Ar { get; set; }
        public string Name_En { get; set; }
        public string Address_Ar { get; set; }
        public string Address_En { get; set; }
        public Nullable<int> PublicOrgType_ID { get; set; }
        public bool IsNational { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IS_OnlineOffline { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<short> Center_ID { get; set; }
        public Nullable<short> Village_ID { get; set; }
        public Nullable<short> Person_Responsible_Country_ID { get; set; }
        public string Person_Responsible_Name { get; set; }
        public string Person_Responsible_Job { get; set; }
        public string Person_Responsible_Address { get; set; }
        public Nullable<int> Person_IDType { get; set; }
        public string PersonResponsible_IDNumber { get; set; }
        public Nullable<short> User_Activation_Id { get; set; }
        public Nullable<System.DateTime> User_Activation_Date { get; set; }
    
        public virtual PublicOrganization_Type PublicOrganization_Type { get; set; }
    }
}
