//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refuse_Reason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Refuse_Reason()
        {
            this.Ex_CheckRequest_RefuseReason = new HashSet<Ex_CheckRequest_RefuseReason>();
            this.Farm_Request_Refuse_Reason = new HashSet<Farm_Request_Refuse_Reason>();
            this.Im_CheckRequest_RefuseReason = new HashSet<Im_CheckRequest_RefuseReason>();
            this.Im_PermissionRequest_RefuseReason = new HashSet<Im_PermissionRequest_RefuseReason>();
        }
    
        public short ID { get; set; }
        public string Name_Ar { get; set; }
        public string Name_En { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsStop { get; set; }
        public long User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<long> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<long> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<int> IsExport { get; set; }
        public Nullable<int> Refused_stopped { get; set; }
        public Nullable<int> A_SystemCode_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_RefuseReason> Ex_CheckRequest_RefuseReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm_Request_Refuse_Reason> Farm_Request_Refuse_Reason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CheckRequest_RefuseReason> Im_CheckRequest_RefuseReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_PermissionRequest_RefuseReason> Im_PermissionRequest_RefuseReason { get; set; }
    }
}
