//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Station()
        {
            this.Ex_CheckRequest_Places = new HashSet<Ex_CheckRequest_Places>();
            this.Ex_CheckRequest_Places1 = new HashSet<Ex_CheckRequest_Places>();
            this.Im_CustodyPlace_CheckRequest = new HashSet<Im_CustodyPlace_CheckRequest>();
            this.Station_Accreditation_Request = new HashSet<Station_Accreditation_Request>();
            this.Station_Accreditation = new HashSet<Station_Accreditation>();
            this.Station_Emp = new HashSet<Station_Emp>();
            this.Station_Managing_Director = new HashSet<Station_Managing_Director>();
            this.StationContacts = new HashSet<StationContact>();
        }
    
        public long ID { get; set; }
        public string Ar_Name { get; set; }
        public string En_Name { get; set; }
        public string Address_Ar { get; set; }
        public string Address_En { get; set; }
        public string StationCode { get; set; }
        public string TaxesRecord { get; set; }
        public string CommertialRecord { get; set; }
        public string Industrial_License_Num { get; set; }
        public string FileUpload { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<short> Gov_Id { get; set; }
        public Nullable<short> Center_Id { get; set; }
        public Nullable<short> Village_Id { get; set; }
        public Nullable<int> User_Type_Id { get; set; }
        public Nullable<long> Company_ID { get; set; }
        public Nullable<System.DateTime> EndDate_Industrial_License_Num { get; set; }
        public Nullable<System.DateTime> StartDate_Industrial_License_Num { get; set; }
        public Nullable<int> working_hours { get; set; }
        public Nullable<int> Average_number_workers { get; set; }
        public Nullable<int> Number_Shifts { get; set; }
        public Nullable<int> Number_working_Days { get; set; }
        public Nullable<byte> Seasonal_Annual { get; set; }
        public Nullable<int> Year_Creation { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<decimal> Facility_area { get; set; }
        public Nullable<decimal> The_num_of_storage_refrigerators { get; set; }
        public Nullable<decimal> Storage_fridge_capacity { get; set; }
        public Nullable<decimal> Fast_cooling_refrigerators { get; set; }
        public Nullable<decimal> The_num_of_production_lines { get; set; }
        public Nullable<decimal> Production_capacity { get; set; }
        public string Notes_Reject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Places> Ex_CheckRequest_Places { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_CheckRequest_Places> Ex_CheckRequest_Places1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_CustodyPlace_CheckRequest> Im_CustodyPlace_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation_Request> Station_Accreditation_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation> Station_Accreditation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Emp> Station_Emp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Managing_Director> Station_Managing_Director { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationContact> StationContacts { get; set; }
    }
}
