//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_Data
    {
        public long Station_ID { get; set; }
        public string Ar_Name { get; set; }
        public string StationCode { get; set; }
        public Nullable<long> Company_ID { get; set; }
        public Nullable<short> Gov_Id { get; set; }
        public Nullable<short> Center_Id { get; set; }
        public Nullable<short> Village_Id { get; set; }
        public string Gov_Ar_Name { get; set; }
        public string Center_Ar_Name { get; set; }
        public string Village_Ar_Name { get; set; }
        public Nullable<bool> station_IsActive { get; set; }
        public Nullable<bool> station_IsAccepted { get; set; }
        public Nullable<short> Station_User_Deletion_Id { get; set; }
        public string Company_Name { get; set; }
    }
}
