//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_Accreditation_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Station_Accreditation_Request()
        {
            this.Station_Accreditation_Committee = new HashSet<Station_Accreditation_Committee>();
            this.Station_Accreditation_Request_Fees = new HashSet<Station_Accreditation_Request_Fees>();
        }
    
        public long ID { get; set; }
        public long Station_ID { get; set; }
        public long Station_Accreditation_Data_ID { get; set; }
        public byte Station_Accreditation_Request_Type_ID { get; set; }
        public string Notes_Quarantine { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<decimal> Amount_Total { get; set; }
        public Nullable<byte> CommitteeType_ID { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> Is_Final_requst { get; set; }
    
        public virtual CommitteeType CommitteeType { get; set; }
        public virtual Station Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation_Committee> Station_Accreditation_Committee { get; set; }
        public virtual Station_Accreditation_Data Station_Accreditation_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation_Request_Fees> Station_Accreditation_Request_Fees { get; set; }
        public virtual Station_Accreditation_Request_Type Station_Accreditation_Request_Type { get; set; }
    }
}
