//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_Accreditation_Committee_Imge
    {
        public long ID { get; set; }
        public long Station_Accreditation_Committee_id { get; set; }
        public string Infection_Comment { get; set; }
        public byte[] AttachmentPath_Binary { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
    
        public virtual Station_Accreditation_Committee Station_Accreditation_Committee { get; set; }
    }
}
