//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_Requst
    {
        public long Station_Accreditation_Data_ID { get; set; }
        public byte Station_Accreditation_Request_Type_ID { get; set; }
        public Nullable<bool> Station_Accreditation_Request_ISActive { get; set; }
        public Nullable<bool> Station_Accreditation_Request_ISpaid { get; set; }
        public Nullable<bool> Station_Accreditation_Request_IsAccepted { get; set; }
        public Nullable<bool> Is_Final_requst { get; set; }
        public string Station_Accreditation_Data_Name { get; set; }
        public Nullable<bool> Station_Accreditation_Data_IsActive { get; set; }
        public string Station_Accreditation_Request_Type_Name { get; set; }
        public Nullable<bool> Station_Accreditation_Request_Type_IsActive { get; set; }
        public long Station_ID { get; set; }
        public long Station_Accreditation_Request_ID { get; set; }
        public Nullable<int> Accreditation_Type_ID { get; set; }
        public Nullable<byte> StationActivityType_ID { get; set; }
        public Nullable<short> Request_User_Deletion_Id { get; set; }
    }
}
