//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_Committee
    {
        public long Station_Accreditation_Committee_ID { get; set; }
        public long Station_Accreditation_Request_ID { get; set; }
        public Nullable<System.DateTime> Delegation_Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> Is_Start_Android { get; set; }
        public Nullable<bool> Is_Cancel { get; set; }
        public Nullable<short> Committee_User_Deletion_Id { get; set; }
    }
}
