//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_Accreditation_Committee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Station_Accreditation_Committee()
        {
            this.Station_Accreditation_Committee_Final_Result = new HashSet<Station_Accreditation_Committee_Final_Result>();
            this.Station_Accreditation_Committee_Imge = new HashSet<Station_Accreditation_Committee_Imge>();
            this.Station_Accreditation_Committee_Shift = new HashSet<Station_Accreditation_Committee_Shift>();
            this.Station_Accreditation_Committee_CheckList = new HashSet<Station_Accreditation_Committee_CheckList>();
            this.Station_Accreditation_Request_Fees_ENG = new HashSet<Station_Accreditation_Request_Fees_ENG>();
        }
    
        public long ID { get; set; }
        public long Station_Accreditation_Request_ID { get; set; }
        public byte CommitteeType_ID { get; set; }
        public Nullable<System.DateTime> Delegation_Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public decimal Amount_Total { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
        public string Notes_Refuse_En { get; set; }
        public string Notes_Refuse_Ar { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> Is_Start_Android { get; set; }
        public Nullable<bool> Is_Cancel { get; set; }
    
        public virtual CommitteeType CommitteeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation_Committee_Final_Result> Station_Accreditation_Committee_Final_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation_Committee_Imge> Station_Accreditation_Committee_Imge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation_Committee_Shift> Station_Accreditation_Committee_Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation_Committee_CheckList> Station_Accreditation_Committee_CheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station_Accreditation_Request_Fees_ENG> Station_Accreditation_Request_Fees_ENG { get; set; }
        public virtual Station_Accreditation_Request Station_Accreditation_Request { get; set; }
    }
}
