//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Action()
        {
            this.Table_Action_Log = new HashSet<Table_Action_Log>();
            this.Table_Action_Log_CheckRequest = new HashSet<Table_Action_Log_CheckRequest>();
            this.Table_Action_Log_EX = new HashSet<Table_Action_Log_EX>();
            this.Table_Action_Log_Farm = new HashSet<Table_Action_Log_Farm>();
            this.Table_Action_Log_Station = new HashSet<Table_Action_Log_Station>();
        }
    
        public short ID { get; set; }
        public short ID_Table_Name { get; set; }
        public string Name_Ar { get; set; }
        public string Name_En { get; set; }
        public string NOTS_Ar { get; set; }
        public string NOTS_En { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string NOTS { get; set; }
    
        public virtual A_AttachmentTableName A_AttachmentTableName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Action_Log> Table_Action_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Action_Log_CheckRequest> Table_Action_Log_CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Action_Log_EX> Table_Action_Log_EX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Action_Log_Farm> Table_Action_Log_Farm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Action_Log_Station> Table_Action_Log_Station { get; set; }
    }
}
