//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Action_Log
    {
        public long ID { get; set; }
        public short ID_Table_Action { get; set; }
        public Nullable<long> ID_TableActionValue { get; set; }
        public Nullable<long> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public string NOTS { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<int> User_Type_ID { get; set; }
        public Nullable<int> Type_log_ID { get; set; }
        public Nullable<long> Im_PermissionRequest_ID { get; set; }
    
        public virtual Table_Action Table_Action { get; set; }
    }
}
