//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TreatmentMaterial()
        {
            this.Ex_Request_TreatmentData = new HashSet<Ex_Request_TreatmentData>();
            this.Im_Request_TreatmentData = new HashSet<Im_Request_TreatmentData>();
        }
    
        public byte ID { get; set; }
        public Nullable<long> Item_ID { get; set; }
        public Nullable<byte> TreatmentMethods_ID { get; set; }
        public bool IsActive { get; set; }
        public string ChemicalComposition { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public short User_Creation_Id { get; set; }
        public System.DateTime User_Creation_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_Request_TreatmentData> Ex_Request_TreatmentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Im_Request_TreatmentData> Im_Request_TreatmentData { get; set; }
        public virtual Item Item { get; set; }
        public virtual TreatmentMethod TreatmentMethod { get; set; }
    }
}
