//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TYPE
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public bool IsCompany { get; set; }
        public long IDSource { get; set; }
        public Nullable<bool> ISAdmin { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<long> User_Delete_Id { get; set; }
        public Nullable<System.DateTime> User_Delete_Date { get; set; }
        public Nullable<long> User_Updata_Id { get; set; }
        public Nullable<System.DateTime> User_Updata_Date { get; set; }
    }
}
