//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Websitetype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Websitetype()
        {
            this.WebsiteTypeDetails = new HashSet<WebsiteTypeDetail>();
        }
    
        public int ID { get; set; }
        public string TypeAr { get; set; }
        public string TypeEN { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteTypeDetail> WebsiteTypeDetails { get; set; }
    }
}
