//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantQuar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteTypeDetail
    {
        public int ID { get; set; }
        public string TitleAr { get; set; }
        public string TitleEn { get; set; }
        public string descAr { get; set; }
        public string descEn { get; set; }
        public string filepath { get; set; }
        public Nullable<int> WebsitetypeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> User_Updation_Id { get; set; }
        public Nullable<System.DateTime> User_Updation_Date { get; set; }
        public Nullable<short> User_Deletion_Id { get; set; }
        public Nullable<System.DateTime> User_Deletion_Date { get; set; }
        public Nullable<short> User_Creation_Id { get; set; }
        public Nullable<System.DateTime> User_Creation_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string linkURL { get; set; }
    
        public virtual Websitetype Websitetype { get; set; }
    }
}
