//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbPrivilageEntities : DbContext
    {
        public dbPrivilageEntities()
            : base("name=dbPrivilageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Error_Save> Error_Save { get; set; }
        public virtual DbSet<PR_Admin> PR_Admin { get; set; }
        public virtual DbSet<PR_Application> PR_Application { get; set; }
        public virtual DbSet<PR_ApplicationCategory> PR_ApplicationCategory { get; set; }
        public virtual DbSet<PR_Group> PR_Group { get; set; }
        public virtual DbSet<PR_GroupModuleMenu> PR_GroupModuleMenu { get; set; }
        public virtual DbSet<PR_GroupModuleMenuConstraint> PR_GroupModuleMenuConstraint { get; set; }
        public virtual DbSet<PR_GroupModuleMenuPrivilage> PR_GroupModuleMenuPrivilage { get; set; }
        public virtual DbSet<PR_Menu> PR_Menu { get; set; }
        public virtual DbSet<PR_MenuConstraint> PR_MenuConstraint { get; set; }
        public virtual DbSet<PR_Mission> PR_Mission { get; set; }
        public virtual DbSet<PR_Module> PR_Module { get; set; }
        public virtual DbSet<PR_Setting> PR_Setting { get; set; }
        public virtual DbSet<PR_User> PR_User { get; set; }
        public virtual DbSet<PR_UserGroup> PR_UserGroup { get; set; }
        public virtual DbSet<PR_UserWorkPlace> PR_UserWorkPlace { get; set; }
    
        [DbFunction("dbPrivilageEntities", "FN_PR_GEtALLmenuPrivilage")]
        public virtual IQueryable<FN_PR_GEtALLmenuPrivilage_Result> FN_PR_GEtALLmenuPrivilage(Nullable<int> pR_ApplicationCategoryId, Nullable<int> pR_ModuleId, Nullable<short> pR_UserId, Nullable<bool> is_Group, Nullable<int> language)
        {
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            var pR_ModuleIdParameter = pR_ModuleId.HasValue ?
                new ObjectParameter("PR_ModuleId", pR_ModuleId) :
                new ObjectParameter("PR_ModuleId", typeof(int));
    
            var pR_UserIdParameter = pR_UserId.HasValue ?
                new ObjectParameter("PR_UserId", pR_UserId) :
                new ObjectParameter("PR_UserId", typeof(short));
    
            var is_GroupParameter = is_Group.HasValue ?
                new ObjectParameter("Is_Group", is_Group) :
                new ObjectParameter("Is_Group", typeof(bool));
    
            var languageParameter = language.HasValue ?
                new ObjectParameter("Language", language) :
                new ObjectParameter("Language", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_PR_GEtALLmenuPrivilage_Result>("[dbPrivilageEntities].[dbPrivilageEntities.FN_PR_GEtALLmenuPrivilage](@PR_ApplicationCategoryId, @PR_ModuleId, @PR_UserId, @Is_Group, @Language)", pR_ApplicationCategoryIdParameter, pR_ModuleIdParameter, pR_UserIdParameter, is_GroupParameter, languageParameter);
        }
    
        public virtual ObjectResult<GetGroupsNameByUserAndApplication_Result> GetGroupsNameByUserAndApplication(Nullable<short> pR_UserId, Nullable<int> pR_ApplicationCategoryId, Nullable<int> language)
        {
            var pR_UserIdParameter = pR_UserId.HasValue ?
                new ObjectParameter("PR_UserId", pR_UserId) :
                new ObjectParameter("PR_UserId", typeof(short));
    
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            var languageParameter = language.HasValue ?
                new ObjectParameter("Language", language) :
                new ObjectParameter("Language", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGroupsNameByUserAndApplication_Result>("dbPrivilageEntities.GetGroupsNameByUserAndApplication", pR_UserIdParameter, pR_ApplicationCategoryIdParameter, languageParameter);
        }
    
        public virtual ObjectResult<GetModulNameByUserAndApplicationandGroup_Result> GetModulNameByUserAndApplicationandGroup(Nullable<short> pR_UserId, Nullable<int> pR_GroupId, Nullable<int> language)
        {
            var pR_UserIdParameter = pR_UserId.HasValue ?
                new ObjectParameter("PR_UserId", pR_UserId) :
                new ObjectParameter("PR_UserId", typeof(short));
    
            var pR_GroupIdParameter = pR_GroupId.HasValue ?
                new ObjectParameter("PR_GroupId", pR_GroupId) :
                new ObjectParameter("PR_GroupId", typeof(int));
    
            var languageParameter = language.HasValue ?
                new ObjectParameter("Language", language) :
                new ObjectParameter("Language", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetModulNameByUserAndApplicationandGroup_Result>("dbPrivilageEntities.GetModulNameByUserAndApplicationandGroup", pR_UserIdParameter, pR_GroupIdParameter, languageParameter);
        }
    
        public virtual int Sp_Admin_Error_Insert(string pageName, string errorMessage, string functionName)
        {
            var pageNameParameter = pageName != null ?
                new ObjectParameter("PageName", pageName) :
                new ObjectParameter("PageName", typeof(string));
    
            var errorMessageParameter = errorMessage != null ?
                new ObjectParameter("ErrorMessage", errorMessage) :
                new ObjectParameter("ErrorMessage", typeof(string));
    
            var functionNameParameter = functionName != null ?
                new ObjectParameter("FunctionName", functionName) :
                new ObjectParameter("FunctionName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbPrivilageEntities.Sp_Admin_Error_Insert", pageNameParameter, errorMessageParameter, functionNameParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbPrivilageEntities.sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbPrivilageEntities.sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbPrivilageEntities.sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbPrivilageEntities.sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbPrivilageEntities.sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_PR_GetAllMenuFilterList_Result> SP_PR_GetAllMenuFilterList(Nullable<int> pR_ApplicationCategoryId, Nullable<int> pR_ApplicationId, Nullable<int> pR_ModuleId, Nullable<int> jtStartIndex, Nullable<int> jtPageSize)
        {
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            var pR_ApplicationIdParameter = pR_ApplicationId.HasValue ?
                new ObjectParameter("PR_ApplicationId", pR_ApplicationId) :
                new ObjectParameter("PR_ApplicationId", typeof(int));
    
            var pR_ModuleIdParameter = pR_ModuleId.HasValue ?
                new ObjectParameter("PR_ModuleId", pR_ModuleId) :
                new ObjectParameter("PR_ModuleId", typeof(int));
    
            var jtStartIndexParameter = jtStartIndex.HasValue ?
                new ObjectParameter("jtStartIndex", jtStartIndex) :
                new ObjectParameter("jtStartIndex", typeof(int));
    
            var jtPageSizeParameter = jtPageSize.HasValue ?
                new ObjectParameter("jtPageSize", jtPageSize) :
                new ObjectParameter("jtPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PR_GetAllMenuFilterList_Result>("dbPrivilageEntities.SP_PR_GetAllMenuFilterList", pR_ApplicationCategoryIdParameter, pR_ApplicationIdParameter, pR_ModuleIdParameter, jtStartIndexParameter, jtPageSizeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_PR_GetAllMenuFilterListCount(Nullable<int> pR_ApplicationCategoryId, Nullable<int> pR_ApplicationId, Nullable<int> pR_ModuleId)
        {
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            var pR_ApplicationIdParameter = pR_ApplicationId.HasValue ?
                new ObjectParameter("PR_ApplicationId", pR_ApplicationId) :
                new ObjectParameter("PR_ApplicationId", typeof(int));
    
            var pR_ModuleIdParameter = pR_ModuleId.HasValue ?
                new ObjectParameter("PR_ModuleId", pR_ModuleId) :
                new ObjectParameter("PR_ModuleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dbPrivilageEntities.SP_PR_GetAllMenuFilterListCount", pR_ApplicationCategoryIdParameter, pR_ApplicationIdParameter, pR_ModuleIdParameter);
        }
    
        public virtual ObjectResult<SP_PR_GetAllMenuSuperPrivilageBy_AppCatId_ModuleId_UserId_Result> SP_PR_GetAllMenuSuperPrivilageBy_AppCatId_ModuleId_UserId(Nullable<int> pR_ApplicationCategoryId, Nullable<int> pR_ModuleId, Nullable<short> pR_UserId, Nullable<bool> is_Group, Nullable<int> language)
        {
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            var pR_ModuleIdParameter = pR_ModuleId.HasValue ?
                new ObjectParameter("PR_ModuleId", pR_ModuleId) :
                new ObjectParameter("PR_ModuleId", typeof(int));
    
            var pR_UserIdParameter = pR_UserId.HasValue ?
                new ObjectParameter("PR_UserId", pR_UserId) :
                new ObjectParameter("PR_UserId", typeof(short));
    
            var is_GroupParameter = is_Group.HasValue ?
                new ObjectParameter("Is_Group", is_Group) :
                new ObjectParameter("Is_Group", typeof(bool));
    
            var languageParameter = language.HasValue ?
                new ObjectParameter("Language", language) :
                new ObjectParameter("Language", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PR_GetAllMenuSuperPrivilageBy_AppCatId_ModuleId_UserId_Result>("dbPrivilageEntities.SP_PR_GetAllMenuSuperPrivilageBy_AppCatId_ModuleId_UserId", pR_ApplicationCategoryIdParameter, pR_ModuleIdParameter, pR_UserIdParameter, is_GroupParameter, languageParameter);
        }
    
        public virtual ObjectResult<SP_PR_GetAllModuleFilterList_Result> SP_PR_GetAllModuleFilterList(Nullable<int> pR_ApplicationCategoryId, Nullable<int> pR_ApplicationId, Nullable<int> jtStartIndex, Nullable<int> jtPageSize)
        {
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            var pR_ApplicationIdParameter = pR_ApplicationId.HasValue ?
                new ObjectParameter("PR_ApplicationId", pR_ApplicationId) :
                new ObjectParameter("PR_ApplicationId", typeof(int));
    
            var jtStartIndexParameter = jtStartIndex.HasValue ?
                new ObjectParameter("jtStartIndex", jtStartIndex) :
                new ObjectParameter("jtStartIndex", typeof(int));
    
            var jtPageSizeParameter = jtPageSize.HasValue ?
                new ObjectParameter("jtPageSize", jtPageSize) :
                new ObjectParameter("jtPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PR_GetAllModuleFilterList_Result>("dbPrivilageEntities.SP_PR_GetAllModuleFilterList", pR_ApplicationCategoryIdParameter, pR_ApplicationIdParameter, jtStartIndexParameter, jtPageSizeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_PR_GetAllModuleFilterListCount(Nullable<int> pR_ApplicationCategoryId, Nullable<int> pR_ApplicationId)
        {
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            var pR_ApplicationIdParameter = pR_ApplicationId.HasValue ?
                new ObjectParameter("PR_ApplicationId", pR_ApplicationId) :
                new ObjectParameter("PR_ApplicationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dbPrivilageEntities.SP_PR_GetAllModuleFilterListCount", pR_ApplicationCategoryIdParameter, pR_ApplicationIdParameter);
        }
    
        public virtual ObjectResult<SP_PR_GetGroupsByUserIdAndAppCategoryId_Result> SP_PR_GetGroupsByUserIdAndAppCategoryId(Nullable<short> pR_UserId, Nullable<int> pR_ApplicationCategoryId, Nullable<int> jtStartIndex, Nullable<int> jtPageSize)
        {
            var pR_UserIdParameter = pR_UserId.HasValue ?
                new ObjectParameter("PR_UserId", pR_UserId) :
                new ObjectParameter("PR_UserId", typeof(short));
    
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            var jtStartIndexParameter = jtStartIndex.HasValue ?
                new ObjectParameter("jtStartIndex", jtStartIndex) :
                new ObjectParameter("jtStartIndex", typeof(int));
    
            var jtPageSizeParameter = jtPageSize.HasValue ?
                new ObjectParameter("jtPageSize", jtPageSize) :
                new ObjectParameter("jtPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PR_GetGroupsByUserIdAndAppCategoryId_Result>("dbPrivilageEntities.SP_PR_GetGroupsByUserIdAndAppCategoryId", pR_UserIdParameter, pR_ApplicationCategoryIdParameter, jtStartIndexParameter, jtPageSizeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_PR_GetGroupsByUserIdAndAppCategoryIdCount(Nullable<short> pR_UserId, Nullable<int> pR_ApplicationCategoryId)
        {
            var pR_UserIdParameter = pR_UserId.HasValue ?
                new ObjectParameter("PR_UserId", pR_UserId) :
                new ObjectParameter("PR_UserId", typeof(short));
    
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dbPrivilageEntities.SP_PR_GetGroupsByUserIdAndAppCategoryIdCount", pR_UserIdParameter, pR_ApplicationCategoryIdParameter);
        }
    
        public virtual ObjectResult<SP_PR_GetUserAllInfoById_Result> SP_PR_GetUserAllInfoById(Nullable<short> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PR_GetUserAllInfoById_Result>("dbPrivilageEntities.SP_PR_GetUserAllInfoById", userIdParameter);
        }
    
        public virtual int SP_PR_UserGetDetails(Nullable<short> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbPrivilageEntities.SP_PR_UserGetDetails", idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbPrivilageEntities.sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbPrivilageEntities.sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<GetMenuUser_Result> GetMenuUser(Nullable<int> pR_ApplicationCategoryId, Nullable<int> pR_ModuleId, Nullable<short> pR_UserId, Nullable<int> groupID, Nullable<int> language)
        {
            var pR_ApplicationCategoryIdParameter = pR_ApplicationCategoryId.HasValue ?
                new ObjectParameter("PR_ApplicationCategoryId", pR_ApplicationCategoryId) :
                new ObjectParameter("PR_ApplicationCategoryId", typeof(int));
    
            var pR_ModuleIdParameter = pR_ModuleId.HasValue ?
                new ObjectParameter("PR_ModuleId", pR_ModuleId) :
                new ObjectParameter("PR_ModuleId", typeof(int));
    
            var pR_UserIdParameter = pR_UserId.HasValue ?
                new ObjectParameter("PR_UserId", pR_UserId) :
                new ObjectParameter("PR_UserId", typeof(short));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var languageParameter = language.HasValue ?
                new ObjectParameter("Language", language) :
                new ObjectParameter("Language", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMenuUser_Result>("dbPrivilageEntities.GetMenuUser", pR_ApplicationCategoryIdParameter, pR_ModuleIdParameter, pR_UserIdParameter, groupIDParameter, languageParameter);
        }
    }
}
