//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_ApplicationCategory
    {
        public int Id { get; set; }
        public string PR_ApplicationCategoryName { get; set; }
        public string ApplicationURL { get; set; }
        public string ApplicationCategoryDescription { get; set; }
    }
}
