//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_GroupModuleMenuPrivilage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PR_GroupModuleMenuPrivilage()
        {
            this.PR_GroupModuleMenuConstraint = new HashSet<PR_GroupModuleMenuConstraint>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PR_GroupId { get; set; }
        public Nullable<int> PR_ModuleId { get; set; }
        public Nullable<int> PR_MenuId { get; set; }
        public bool CanView { get; set; }
        public bool CanAdd { get; set; }
        public bool CanEdit { get; set; }
        public bool CanDelete { get; set; }
        public Nullable<bool> CanPrint { get; set; }
        public Nullable<short> PR_User_id { get; set; }
        public Nullable<bool> IS_Active { get; set; }
    
        public virtual PR_Group PR_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_GroupModuleMenuConstraint> PR_GroupModuleMenuConstraint { get; set; }
        public virtual PR_Menu PR_Menu { get; set; }
        public virtual PR_Module PR_Module { get; set; }
        public virtual PR_User PR_User { get; set; }
    }
}
