//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_GroupModuleMenu
    {
        public int PR_GroupId { get; set; }
        public int PR_ModuleId { get; set; }
        public int PR_MenuId { get; set; }
        public Nullable<bool> IS_Active { get; set; }
        public Nullable<int> Order_BY { get; set; }
    
        public virtual PR_Group PR_Group { get; set; }
        public virtual PR_Menu PR_Menu { get; set; }
        public virtual PR_Module PR_Module { get; set; }
    }
}
