//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_GroupModuleMenuConstraint
    {
        public int Id { get; set; }
        public Nullable<int> PR_GroupModuleMenuPrivilageId { get; set; }
        public Nullable<int> PR_MenuConstraintId { get; set; }
    
        public virtual PR_GroupModuleMenuPrivilage PR_GroupModuleMenuPrivilage { get; set; }
        public virtual PR_MenuConstraint PR_MenuConstraint { get; set; }
    }
}
