//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PR_Group()
        {
            this.PR_GroupModuleMenu = new HashSet<PR_GroupModuleMenu>();
            this.PR_GroupModuleMenuPrivilage = new HashSet<PR_GroupModuleMenuPrivilage>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string GroupName_En { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> PR_ApplicationId { get; set; }
        public Nullable<int> PR_ApplicationCategoryId { get; set; }
        public bool IsMinistry { get; set; }
    
        public virtual PR_Application PR_Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_GroupModuleMenu> PR_GroupModuleMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_GroupModuleMenuPrivilage> PR_GroupModuleMenuPrivilage { get; set; }
    }
}
