//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PR_Menu()
        {
            this.PR_GroupModuleMenu = new HashSet<PR_GroupModuleMenu>();
            this.PR_GroupModuleMenuPrivilage = new HashSet<PR_GroupModuleMenuPrivilage>();
            this.PR_MenuConstraint = new HashSet<PR_MenuConstraint>();
        }
    
        public int Id { get; set; }
        public string MenuTitle { get; set; }
        public string MenuTitle_En { get; set; }
        public string MenuURL { get; set; }
        public Nullable<int> PR_MenuId { get; set; }
        public bool Active { get; set; }
        public Nullable<int> PR_ModuleId { get; set; }
        public Nullable<int> PR_ApplicationId { get; set; }
        public Nullable<int> PR_ApplicationCategoryId { get; set; }
        public Nullable<int> Group_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_GroupModuleMenu> PR_GroupModuleMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_GroupModuleMenuPrivilage> PR_GroupModuleMenuPrivilage { get; set; }
        public virtual PR_Module PR_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_MenuConstraint> PR_MenuConstraint { get; set; }
    }
}
