//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PR_Module()
        {
            this.PR_GroupModuleMenu = new HashSet<PR_GroupModuleMenu>();
            this.PR_GroupModuleMenuPrivilage = new HashSet<PR_GroupModuleMenuPrivilage>();
            this.PR_Menu = new HashSet<PR_Menu>();
            this.PR_Setting = new HashSet<PR_Setting>();
        }
    
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public string ModuleName_En { get; set; }
        public string ModuleDescription { get; set; }
        public Nullable<int> PR_ApplicationId { get; set; }
        public Nullable<int> PR_ApplicationCategoryId { get; set; }
        public bool Active { get; set; }
    
        public virtual PR_Application PR_Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_GroupModuleMenu> PR_GroupModuleMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_GroupModuleMenuPrivilage> PR_GroupModuleMenuPrivilage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_Menu> PR_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_Setting> PR_Setting { get; set; }
    }
}
