//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_MenuConstraint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PR_MenuConstraint()
        {
            this.PR_GroupModuleMenuConstraint = new HashSet<PR_GroupModuleMenuConstraint>();
        }
    
        public int Id { get; set; }
        public string ConstraintName { get; set; }
        public Nullable<int> PR_MenuId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_GroupModuleMenuConstraint> PR_GroupModuleMenuConstraint { get; set; }
        public virtual PR_Menu PR_Menu { get; set; }
    }
}
