//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privilages.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_UserWorkPlace
    {
        public int Id { get; set; }
        public Nullable<short> PR_UserId { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsSecurity { get; set; }
        public bool IsMinistry { get; set; }
        public Nullable<short> LK_DirectorateId { get; set; }
        public Nullable<short> LK_ZoneId { get; set; }
        public Nullable<short> LK_OfficeId { get; set; }
        public bool IsCurrentWork { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<short> LK_CenterDepartmentId { get; set; }
        public bool IsTrainingCenter { get; set; }
        public Nullable<int> TS_TrainingCenterId { get; set; }
    
        public virtual PR_User PR_User { get; set; }
    }
}
